import 'server-only'
import type { PrepQuestion } from './prep-types'

export const SYSTEM_DESIGN_BANK: PrepQuestion[] = [
  // ─── Caching (sd-001–sd-008) ─────────────────────────────────────────────

  {
    id: 'sd-001',
    topic: 'caching',
    difficulty: 'junior',
    prompt: 'Design a caching layer for a read-heavy API that serves user profile data.',
    hints: [
      'Clarify cache hit rate target and acceptable staleness (TTL)',
      'Choose between cache-aside, read-through, and write-through strategies',
      'Discuss Redis vs in-process (LRU map) and when to use each',
      'Handle cache invalidation when profiles are updated — avoid stale reads',
    ],
    concepts: ['cache-aside-pattern', 'cache-eviction-policies', 'ttl-and-staleness'],
    companies: ['stripe', 'shopify', 'linkedin'],
  },
  {
    id: 'sd-002',
    topic: 'caching',
    difficulty: 'mid',
    prompt: 'Design a CDN for a video streaming platform. How does content get cached at edge nodes?',
    hints: [
      'Distinguish between static assets (forever-cacheable) and video segments (TTL-based)',
      'Explain how edge nodes pull from origin on a cache miss (pull CDN)',
      'Discuss cache key design — URL path, query params, geographic region',
      'Handle cache invalidation for updated content without purging the whole CDN',
    ],
    concepts: ['cdn-edge-caching', 'cache-eviction-policies', 'consistent-hashing'],
    companies: ['netflix', 'cloudflare', 'youtube'],
  },
  {
    id: 'sd-003',
    topic: 'caching',
    difficulty: 'mid',
    prompt: 'Your Redis cache is being hit with thundering herd when a popular item expires. How do you fix it?',
    hints: [
      'Define thundering herd: many cache misses simultaneously triggering DB reads for the same key',
      'Discuss mutex/lock-based solutions (only one thread recomputes, others wait)',
      'Explain probabilistic early expiration: refresh slightly before expiry to prevent the cliff',
      'Consider background refresh: always serve stale, async recompute before TTL',
    ],
    concepts: ['thundering-herd', 'ttl-and-staleness', 'cache-eviction-policies'],
    companies: ['twitter', 'reddit', 'pinterest'],
  },
  {
    id: 'sd-004',
    topic: 'caching',
    difficulty: 'senior',
    prompt: 'Design a write-back cache for a high-throughput order management system. What are the failure modes?',
    hints: [
      'Contrast write-back (async flush) vs write-through (sync write to DB) — latency vs durability',
      'Failure mode: cache node crashes before flush → data loss. Mitigation: WAL or replicated cache',
      'Failure mode: inconsistency between cache and DB if flush fails partway. Idempotent flush with retry',
      'Discuss when write-back is worth it (write amplification reduction at scale vs risk)',
    ],
    concepts: ['write-through-write-back', 'cache-eviction-policies', 'ttl-and-staleness'],
    companies: ['amazon', 'shopify', 'stripe'],
  },
  {
    id: 'sd-005',
    topic: 'caching',
    difficulty: 'junior',
    prompt: 'Explain the difference between LRU and LFU cache eviction. When would you choose one over the other?',
    hints: [
      'LRU evicts the least recently used item — good for temporal locality (recently accessed → likely accessed again)',
      'LFU evicts the least frequently used — good for popularity-skewed workloads (hot items never evicted)',
      'LFU is more expensive: requires frequency counters. LRU is O(1) with a doubly-linked list + hash map',
      'Hybrid: LFRU or clock-pro. Real systems (Redis) default to LRU with approximations',
    ],
    concepts: ['cache-eviction-policies'],
    companies: [],
  },
  {
    id: 'sd-006',
    topic: 'caching',
    difficulty: 'senior',
    prompt: 'How would you cache search results for a product search engine where results can change in near-real-time?',
    hints: [
      'Identify the cache key: normalized query string + filters + sort order + pagination offset',
      'Short TTL (30-60s) balances freshness vs load reduction for popular queries',
      'Stale-while-revalidate: serve cached result immediately, trigger async refresh in background',
      'Distinguish between shared cache (same query by many users) and user-personalized results (avoid caching personalized)',
    ],
    concepts: ['ttl-and-staleness', 'cache-aside-pattern'],
    companies: ['amazon', 'elasticsearch', 'algolia'],
  },
  {
    id: 'sd-007',
    topic: 'caching',
    difficulty: 'mid',
    prompt: 'Design a session cache for a web application serving 10 million active users.',
    hints: [
      'Session data per user: ~1-2KB. 10M × 2KB = 20GB — needs a distributed cache cluster',
      'Consistent hashing routes each user_id to a cache node without rehashing on scale-out',
      'Discuss session expiry (absolute TTL vs sliding window) and logout invalidation',
      'Trade-off: sticky sessions (simpler) vs stateless sessions with shared cache (more resilient)',
    ],
    concepts: ['consistent-hashing', 'ttl-and-staleness'],
    companies: ['linkedin', 'salesforce', 'okta'],
  },
  {
    id: 'sd-008',
    topic: 'caching',
    difficulty: 'senior',
    prompt: 'You have a multi-region deployment. How do you keep caches consistent across regions?',
    hints: [
      'Identify what needs cross-region consistency: user auth, inventory counts, payment state — not static content',
      'Regional caches are eventually consistent: accept some staleness for most data',
      'For strong consistency needs: write to primary region first, invalidate regional caches on write',
      'Discuss cache stampede risk during regional failover — warm up new region before routing traffic',
    ],
    concepts: ['consistent-hashing', 'ttl-and-staleness', 'cache-eviction-policies'],
    companies: ['cloudflare', 'stripe', 'github'],
  },

  // ─── Databases (sd-009–sd-018) ───────────────────────────────────────────

  {
    id: 'sd-009',
    topic: 'databases',
    difficulty: 'junior',
    prompt: 'When would you choose a NoSQL database over a relational database?',
    hints: [
      'NoSQL excels at flexible schema (document store), high write throughput (wide-column), or graph traversal',
      'Relational DB wins for complex joins, strong consistency, and normalized data with foreign keys',
      'Common mistake: NoSQL is not faster by default — it makes different tradeoffs (CAP theorem)',
      'Give a concrete example: user activity events (Cassandra) vs financial transactions (Postgres)',
    ],
    concepts: ['cap-theorem', 'acid-vs-base'],
    companies: [],
  },
  {
    id: 'sd-010',
    topic: 'databases',
    difficulty: 'mid',
    prompt: 'Design a sharding strategy for a user table that has grown to 500 million rows.',
    hints: [
      'Choose shard key: user_id is natural. Hash-based vs range-based sharding trade-offs',
      'Hash sharding: even distribution, but range queries (all users created in Jan) span all shards',
      'Range sharding: efficient range queries, but hot shards if new users concentrate in one range',
      'Discuss resharding: consistent hashing minimizes data movement when adding shards',
    ],
    concepts: ['database-sharding', 'consistent-hashing'],
    companies: ['instagram', 'twitter', 'linkedin'],
  },
  {
    id: 'sd-011',
    topic: 'databases',
    difficulty: 'mid',
    prompt: 'Explain read replicas. How do they help, and what problems do they introduce?',
    hints: [
      'Read replicas offload read traffic from the primary — horizontal read scaling',
      'Replication lag: writes go to primary, replicas catch up asynchronously. A read immediately after a write may see stale data',
      'Mitigation: read-your-own-writes — route reads for a user to primary (or the replica that confirmed their write)',
      'Use cases: reporting queries, analytics, search indexing — all tolerate slight staleness',
    ],
    concepts: ['database-replication', 'cap-theorem'],
    companies: ['shopify', 'github', 'airbnb'],
  },
  {
    id: 'sd-012',
    topic: 'databases',
    difficulty: 'senior',
    prompt: 'Design a globally distributed database for a financial application that needs both low latency and strong consistency.',
    hints: [
      'CAP theorem: you cannot have partition tolerance + consistency + availability simultaneously',
      'CockroachDB/Spanner approach: multi-region consensus with Paxos/Raft — CP system with tunable latency',
      'Discuss quorum reads and writes: majority of nodes must agree before commit',
      'Latency trade-off: strong consistency requires cross-region round trips (100-200ms). Use async replication for reads where eventual consistency is acceptable',
    ],
    concepts: ['cap-theorem', 'consensus-algorithms', 'database-replication'],
    companies: ['stripe', 'google', 'cockroachdb'],
  },
  {
    id: 'sd-013',
    topic: 'databases',
    difficulty: 'mid',
    prompt: 'What is the N+1 query problem and how do you fix it?',
    hints: [
      'N+1: fetch 1 parent record, then issue 1 query per child — N queries for N parents',
      'Fix: JOIN (single query), or batch load (WHERE id IN (...)), or DataLoader pattern (batch per request cycle)',
      'ORM hidden N+1: lazy loading triggers queries you don\'t see. Use eager loading (include/preload)',
      'Detection: query count logging, slow query alerts, or APM tracing showing repeated identical queries',
    ],
    concepts: ['database-indexes', 'acid-vs-base'],
    companies: [],
  },
  {
    id: 'sd-014',
    topic: 'databases',
    difficulty: 'junior',
    prompt: 'Explain the difference between ACID and BASE properties in databases.',
    hints: [
      'ACID: Atomicity (all or nothing), Consistency (valid state), Isolation (concurrent txns don\'t interfere), Durability (committed = permanent)',
      'BASE: Basically Available, Soft state, Eventually consistent — accepts temporary inconsistency for availability',
      'ACID is standard for relational DBs; BASE describes many distributed NoSQL systems',
      'Real world: you often want ACID for financial data and BASE for activity feeds',
    ],
    concepts: ['acid-vs-base', 'cap-theorem'],
    companies: [],
  },
  {
    id: 'sd-015',
    topic: 'databases',
    difficulty: 'senior',
    prompt: 'Design the indexing strategy for a multi-tenant SaaS application where each tenant can have up to 10 million rows.',
    hints: [
      'Composite index: (tenant_id, entity_id) as the leading columns for all queries filtered by tenant',
      'Partial index: WHERE tenant_id = X — useful if one tenant is dominant, avoids index bloat for rare tenants',
      'Covering index: include all columns needed for a query to avoid heap fetches',
      'Index on foreign keys: without this, DELETE on parent requires full scan of child table',
    ],
    concepts: ['database-indexes', 'database-sharding'],
    companies: ['salesforce', 'atlassian', 'zendesk'],
  },
  {
    id: 'sd-016',
    topic: 'databases',
    difficulty: 'mid',
    prompt: 'How would you implement optimistic locking to prevent lost updates in a concurrent e-commerce checkout?',
    hints: [
      'Optimistic locking: read version number with record; on write, check version hasn\'t changed (no pessimistic lock held)',
      'Implementation: `UPDATE inventory SET quantity=X, version=v+1 WHERE id=Y AND version=v` — if 0 rows updated, conflict detected',
      'Compare to pessimistic locking (SELECT FOR UPDATE): optimistic is better for low-contention, pessimistic for high-contention',
      'Retry loop on conflict: re-read current state, recompute, re-attempt update',
    ],
    concepts: ['acid-vs-base', 'database-replication'],
    companies: ['shopify', 'amazon', 'stripe'],
  },
  {
    id: 'sd-017',
    topic: 'databases',
    difficulty: 'senior',
    prompt: 'Design a time-series database schema for storing 1 billion IoT sensor readings per day.',
    hints: [
      'Time-series data is append-heavy and query-heavy on time ranges — not suitable for row-oriented OLTP',
      'Column-store (TimescaleDB, ClickHouse): compress readings per time range dramatically (10x+)',
      'Partitioning by time chunk: each chunk holds e.g. 1 week of data. Old chunks can be compressed or moved to cold storage',
      'Downsampling: pre-aggregate older data (minute → hour → day) to keep query speed constant as data grows',
    ],
    concepts: ['database-sharding', 'database-indexes'],
    companies: ['influxdb', 'timescale', 'datadog'],
  },
  {
    id: 'sd-018',
    topic: 'databases',
    difficulty: 'mid',
    prompt: 'Explain two-phase commit (2PC) and its failure modes in a distributed transaction.',
    hints: [
      'Phase 1 (Prepare): coordinator asks all participants to prepare — each votes yes/no and persists to WAL',
      'Phase 2 (Commit): if all voted yes, coordinator sends commit to all; otherwise sends rollback',
      'Failure mode: coordinator crashes after phase 1 — participants hold locks indefinitely waiting for phase 2',
      'Alternative: Saga pattern — break long transaction into local transactions with compensating rollbacks',
    ],
    concepts: ['consensus-algorithms', 'acid-vs-base'],
    companies: ['stripe', 'square', 'google'],
  },

  // ─── Message Queues (sd-019–sd-026) ──────────────────────────────────────

  {
    id: 'sd-019',
    topic: 'message-queues',
    difficulty: 'junior',
    prompt: 'Why would you use a message queue instead of calling a service directly (synchronous RPC)?',
    hints: [
      'Decoupling: producer and consumer don\'t need to be up at the same time',
      'Load leveling: burst of writes queued and consumed at sustainable rate by workers',
      'Retry semantics: if consumer fails, message is re-delivered — unlike a failed HTTP call',
      'Trade-off: introduces latency and eventual consistency — not appropriate for synchronous user-facing flows',
    ],
    concepts: ['message-queue-patterns'],
    companies: [],
  },
  {
    id: 'sd-020',
    topic: 'message-queues',
    difficulty: 'mid',
    prompt: 'Design an event-driven notification system using Kafka. How do you handle at-least-once vs exactly-once delivery?',
    hints: [
      'Kafka guarantees at-least-once by default: consumers re-process on crash-before-commit',
      'Exactly-once requires idempotent producers + transactional consumers — significantly more complex',
      'Practical solution: design consumers to be idempotent (dedupe by event_id in the DB)',
      'Dead letter queue: messages that fail after N retries go to a DLQ for manual inspection',
    ],
    concepts: ['kafka-architecture', 'message-queue-patterns'],
    companies: ['linkedin', 'uber', 'airbnb'],
  },
  {
    id: 'sd-021',
    topic: 'message-queues',
    difficulty: 'mid',
    prompt: 'How does Kafka achieve high throughput compared to traditional message queues like RabbitMQ?',
    hints: [
      'Kafka: sequential disk writes to append-only log — HDD sequential I/O is near SSD speed',
      'Zero-copy: kernel sends data from disk to network without user-space copy (sendfile syscall)',
      'Consumer manages offset: pull-based, batch consumption — no per-message ACK overhead',
      'Partitioning: parallel consumption across partitions; throughput scales with partition count',
    ],
    concepts: ['kafka-architecture'],
    companies: ['confluent', 'linkedin', 'uber'],
  },
  {
    id: 'sd-022',
    topic: 'message-queues',
    difficulty: 'senior',
    prompt: 'Design a fan-out system for a social network where a celebrity post needs to reach 50 million followers within 5 seconds.',
    hints: [
      'Write fan-out: pre-compute each follower\'s feed on post creation — infeasible at 50M followers',
      'Read fan-out (pull model): followers query "posts from people I follow" at read time — expensive at scale',
      'Hybrid: fan-out for normal users, pull-on-read for celebrities above a follower threshold',
      'Message queue as fan-out broker: publish once, workers partition follower list and batch-write to feed stores',
    ],
    concepts: ['message-queue-patterns', 'kafka-architecture'],
    companies: ['twitter', 'instagram', 'facebook'],
  },
  {
    id: 'sd-023',
    topic: 'message-queues',
    difficulty: 'junior',
    prompt: 'What is the outbox pattern and why is it used with message queues?',
    hints: [
      'Problem: write to DB and publish to queue — if queue publish fails after DB write, event is lost',
      'Outbox pattern: write event to an "outbox" table in the same DB transaction as the business record',
      'A separate relay process reads the outbox table and publishes to the queue — guaranteed at-least-once',
      'This turns a distributed transaction into a local transaction + async relay',
    ],
    concepts: ['message-queue-patterns', 'acid-vs-base'],
    companies: ['stripe', 'shopify'],
  },
  {
    id: 'sd-024',
    topic: 'message-queues',
    difficulty: 'mid',
    prompt: 'Design a delayed job queue (e.g., send an email 24 hours after signup).',
    hints: [
      'Naive approach: cron job scanning a DB table — does not scale, has polling lag',
      'Redis sorted set: score = scheduled_at timestamp. Workers poll for items with score <= now()',
      'Dedicated delay queue services: SQS delay queues (max 15 min), or a two-stage queue (immediate + delay)',
      'Failure handling: if worker crashes during processing, job must be retryable (idempotent)',
    ],
    concepts: ['message-queue-patterns'],
    companies: ['sendgrid', 'mailchimp', 'twilio'],
  },
  {
    id: 'sd-025',
    topic: 'message-queues',
    difficulty: 'senior',
    prompt: 'How would you implement ordered message processing across multiple partitions in Kafka?',
    hints: [
      'Kafka guarantees ordering within a partition, not across partitions',
      'Route related messages to the same partition via a partition key (e.g., user_id, order_id)',
      'Global ordering across partitions requires a single partition (eliminates parallelism) or a total-order log',
      'For most systems, per-entity ordering (all events for order 123 in order) is sufficient and achievable with partition keys',
    ],
    concepts: ['kafka-architecture'],
    companies: ['confluent', 'uber', 'robinhood'],
  },
  {
    id: 'sd-026',
    topic: 'message-queues',
    difficulty: 'mid',
    prompt: 'Design a priority queue system where premium users\' jobs are processed before free tier users\'.',
    hints: [
      'Separate queues per priority tier: workers drain high-priority queue before touching low-priority',
      'Weighted polling: worker polls high-priority N times, then low-priority 1 time — prevents starvation',
      'Redis sorted set with priority score: combine priority and enqueue_time to prevent indefinite starvation',
      'Monitor queue depth per tier separately — SLO: premium jobs processed within 5s, free within 60s',
    ],
    concepts: ['message-queue-patterns'],
    companies: ['heroku', 'render', 'salesforce'],
  },

  // ─── Distributed Systems (sd-027–sd-036) ─────────────────────────────────

  {
    id: 'sd-027',
    topic: 'distributed-systems',
    difficulty: 'mid',
    prompt: 'Explain the Raft consensus algorithm at a high level. How does leader election work?',
    hints: [
      'Raft roles: Follower (default), Candidate (requesting votes), Leader (replicates log)',
      'Election: if a follower receives no heartbeat within election timeout, it becomes a candidate and requests votes',
      'Vote granted if candidate\'s log is at least as up-to-date as voter\'s log — prevents electing stale leaders',
      'Leader sends heartbeats to prevent new elections; log entries committed once replicated to majority',
    ],
    concepts: ['consensus-algorithms', 'leader-election'],
    companies: ['etcd', 'cockroachdb', 'consul'],
  },
  {
    id: 'sd-028',
    topic: 'distributed-systems',
    difficulty: 'mid',
    prompt: 'Design a distributed lock service. How do you prevent split-brain?',
    hints: [
      'Use Redis SET NX EX (set if not exists with TTL) for simple single-node distributed locks',
      'Split-brain risk: if lock holder pauses (GC, network partition), TTL expires, new holder acquires — both believe they hold the lock',
      'Fencing token: lock service issues monotonically increasing tokens. Storage system rejects writes with lower token',
      'Redlock (multi-node): acquire majority of N Redis nodes — safer but still has edge cases under clock drift',
    ],
    concepts: ['leader-election', 'consensus-algorithms'],
    companies: ['redislabs', 'zookeeper', 'etcd'],
  },
  {
    id: 'sd-029',
    topic: 'distributed-systems',
    difficulty: 'senior',
    prompt: 'How do you design a system that remains available during a network partition (AP system)?',
    hints: [
      'CAP theorem: choose partition tolerance + availability → accept eventual consistency',
      'Every node responds with its local state during partition — responses may diverge',
      'Conflict resolution: last-write-wins (LWW) using timestamps (clock drift risk), vector clocks, or CRDTs',
      'CRDT (conflict-free replicated data type): data structures that merge automatically without coordination (counters, sets)',
    ],
    concepts: ['cap-theorem', 'consensus-algorithms'],
    companies: ['amazon', 'cassandra', 'riak'],
  },
  {
    id: 'sd-030',
    topic: 'distributed-systems',
    difficulty: 'mid',
    prompt: 'Design a heartbeat and failure detection system for a cluster of 100 nodes.',
    hints: [
      'Naive: every node pings every other node — O(N²) traffic, doesn\'t scale',
      'Gossip protocol: each node randomly selects K neighbors and shares its heartbeat table — information propagates in O(log N)',
      'Phi accrual failure detector: instead of binary up/down, outputs a suspicion level based on heartbeat timing variance',
      'False positive rate vs detection latency trade-off: tighter timeout → faster detection, more false positives under load',
    ],
    concepts: ['leader-election', 'consensus-algorithms'],
    companies: ['cassandra', 'amazon-dynamo', 'consul'],
  },
  {
    id: 'sd-031',
    topic: 'distributed-systems',
    difficulty: 'senior',
    prompt: 'What is the difference between a vector clock and a Lamport timestamp? When would you use each?',
    hints: [
      'Lamport timestamp: logical clock incremented on send/receive. Captures causality only partially (a → b implies L(a) < L(b), but not vice versa)',
      'Vector clock: one logical clock per node. Can detect causal relationships and concurrent events (neither happened before the other)',
      'Vector clock downside: size grows with number of nodes — not practical for large clusters',
      'Use Lamport for ordering events in a small system; vector clocks for detecting conflicts in distributed data stores',
    ],
    concepts: ['consensus-algorithms'],
    companies: ['amazon-dynamo', 'riak'],
  },
  {
    id: 'sd-032',
    topic: 'distributed-systems',
    difficulty: 'mid',
    prompt: 'Design a distributed rate limiter that works across multiple API servers.',
    hints: [
      'Single-server: token bucket or sliding window counter in memory — breaks across multiple servers',
      'Centralized Redis: atomic Lua script or Redis counters — INCR + EXPIRE. Single point of contention at high scale',
      'Sliding window with Redis sorted set: score = timestamp, count members in last N seconds',
      'Approximate distributed: each server tracks locally, syncs to central store every 100ms — accepts small over-count margin',
    ],
    concepts: ['rate-limiting'],
    companies: ['cloudflare', 'stripe', 'github'],
  },
  {
    id: 'sd-033',
    topic: 'distributed-systems',
    difficulty: 'junior',
    prompt: 'Explain the difference between horizontal and vertical scaling. When does each make sense?',
    hints: [
      'Vertical: bigger machine (more CPU, RAM) — simple, no code changes, but has a ceiling and single point of failure',
      'Horizontal: more machines — requires stateless services or external state management (session cache, DB)',
      'Stateful services (DBs) are harder to scale horizontally — need sharding or replication',
      'Cost: vertical has diminishing returns at large scale; horizontal is cost-effective with commodity hardware',
    ],
    concepts: ['database-sharding', 'load-balancing'],
    companies: [],
  },
  {
    id: 'sd-034',
    topic: 'distributed-systems',
    difficulty: 'senior',
    prompt: 'Design a distributed cron job scheduler that guarantees each job runs exactly once even with multiple scheduler nodes.',
    hints: [
      'Naive: multiple scheduler nodes each independently trigger jobs → duplicate execution',
      'Leader election: only the leader triggers jobs; followers take over if leader fails (but gap between failover)',
      'Distributed lock with job claim: any node can pick up a job, but must acquire a lock for the job_id first',
      'Idempotent jobs + exactly-once record: write to DB that job ran before executing — check on every attempt',
    ],
    concepts: ['leader-election', 'consensus-algorithms', 'acid-vs-base'],
    companies: ['airflow', 'temporal', 'github'],
  },
  {
    id: 'sd-035',
    topic: 'distributed-systems',
    difficulty: 'senior',
    prompt: 'How would you implement consistent hashing for a cache cluster, and how does node addition/removal work?',
    hints: [
      'Hash ring: each node owns a range of the hash space. Keys map to the next node clockwise',
      'Virtual nodes (vnodes): each physical node owns multiple points on the ring — avoids uneven distribution',
      'Node addition: new node takes keys from its successor — only keys in its range are rehashed, not all keys',
      'Node removal: successor inherits the leaving node\'s keys — minimal disruption to the rest of the ring',
    ],
    concepts: ['consistent-hashing'],
    companies: ['amazon-dynamo', 'cassandra', 'memcached'],
  },
  {
    id: 'sd-036',
    topic: 'distributed-systems',
    difficulty: 'mid',
    prompt: 'What is backpressure and how do you implement it in a streaming pipeline?',
    hints: [
      'Backpressure: slow consumer signals fast producer to slow down, preventing memory overflow',
      'Unbounded queues + no backpressure = OOM when consumer can\'t keep up with producer',
      'Reactive Streams (Java), gRPC flow control, TCP flow control — all implement backpressure primitives',
      'Application-level: bounded queue blocks producer when full; metrics on queue depth → trigger scaling',
    ],
    concepts: ['message-queue-patterns', 'kafka-architecture'],
    companies: ['netflix', 'akka', 'flink'],
  },

  // ─── API Design (sd-037–sd-044) ──────────────────────────────────────────

  {
    id: 'sd-037',
    topic: 'api-design',
    difficulty: 'junior',
    prompt: 'Design a RESTful API for a todo application. What resources and endpoints would you expose?',
    hints: [
      'Resources: /todos, /todos/:id, /users/:id/todos. Use nouns, not verbs in paths',
      'HTTP verbs: GET (read), POST (create), PUT/PATCH (update), DELETE (delete)',
      'Pagination: cursor-based (more stable for mutable lists) vs offset-based (simpler)',
      'Error responses: structured JSON with error code + human-readable message, not just HTTP status',
    ],
    concepts: ['api-gateway'],
    companies: [],
  },
  {
    id: 'sd-038',
    topic: 'api-design',
    difficulty: 'mid',
    prompt: 'When would you choose GraphQL over REST, and what are the operational trade-offs?',
    hints: [
      'GraphQL benefit: clients specify exact fields needed — eliminates over-fetching and under-fetching',
      'GraphQL downside: N+1 query problem at the resolver level — requires DataLoader/batching',
      'Caching: REST resources cache naturally by URL; GraphQL POSTs don\'t cache well at CDN level',
      'Operational complexity: schema versioning, query complexity limits, resolver monitoring are harder',
    ],
    concepts: ['api-gateway', 'rate-limiting'],
    companies: ['github', 'shopify', 'facebook'],
  },
  {
    id: 'sd-039',
    topic: 'api-design',
    difficulty: 'mid',
    prompt: 'Design a rate limiting strategy for a public API with different limits per tier (free: 100/min, paid: 10,000/min).',
    hints: [
      'Token bucket: allows bursts up to bucket size; refills at the rate limit. More user-friendly than fixed window',
      'Per API key rate limiting: each key has its own counter. Enforce at the API gateway, not in app code',
      'Sliding window: more accurate than fixed window (no burst at window boundary), slightly more expensive',
      'Response headers: X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset — communicate limits to clients',
    ],
    concepts: ['rate-limiting', 'api-gateway'],
    companies: ['stripe', 'twilio', 'github'],
  },
  {
    id: 'sd-040',
    topic: 'api-design',
    difficulty: 'senior',
    prompt: 'Design a versioning strategy for a public API that must not break existing clients when you make breaking changes.',
    hints: [
      'URL versioning (/v1/, /v2/): explicit, easy to route, but pollutes URLs and requires duplication',
      'Header versioning (Accept: application/vnd.api+json;version=2): cleaner URLs, harder to test in browser',
      'Maintain old versions for deprecation window (6-12 months), communicate via sunset headers',
      'Non-breaking changes (adding optional fields, new endpoints) can be rolled out without version bump',
    ],
    concepts: ['api-gateway'],
    companies: ['stripe', 'twilio', 'github'],
  },
  {
    id: 'sd-041',
    topic: 'api-design',
    difficulty: 'mid',
    prompt: 'How would you design a webhook delivery system that guarantees delivery even when the recipient server is down?',
    hints: [
      'Retry with exponential backoff: immediate, 1m, 5m, 30m, 2h, 24h — then give up or alert',
      'Persistent storage: write webhook event to DB before delivery attempt — retry on failure',
      'Delivery status tracking: show customers their webhook delivery history with HTTP response codes',
      'Security: sign payloads with HMAC-SHA256 so recipients can verify origin',
    ],
    concepts: ['message-queue-patterns', 'api-gateway'],
    companies: ['stripe', 'github', 'twilio'],
  },
  {
    id: 'sd-042',
    topic: 'api-design',
    difficulty: 'senior',
    prompt: 'Design an API gateway for a microservices architecture. What cross-cutting concerns does it handle?',
    hints: [
      'Auth: verify JWT or API key once at the gateway; downstream services trust the gateway\'s forwarded identity',
      'Rate limiting, request logging, and distributed tracing at the edge — not duplicated in each service',
      'Request routing: path-based routing to services; service discovery integration (Consul, K8s DNS)',
      'Circuit breaker at gateway: if service is unhealthy, fail fast rather than letting requests queue',
    ],
    concepts: ['api-gateway', 'circuit-breaker', 'rate-limiting'],
    companies: ['netflix', 'amazon', 'kong'],
  },
  {
    id: 'sd-043',
    topic: 'api-design',
    difficulty: 'mid',
    prompt: 'How do you design a long-polling or server-sent events (SSE) endpoint for real-time notifications?',
    hints: [
      'Long-polling: client sends request, server holds it open until event or timeout. Simple but wastes connections',
      'SSE: persistent HTTP connection, server pushes events as text/event-stream. One-directional, works through proxies',
      'WebSocket: bidirectional, lower overhead — better for chat or collaborative editing',
      'Connection management: SSE connections tie up a server thread/async slot per client — be aware of connection limits',
    ],
    concepts: ['api-gateway'],
    companies: ['github', 'vercel', 'pusher'],
  },
  {
    id: 'sd-044',
    topic: 'api-design',
    difficulty: 'junior',
    prompt: 'What is idempotency and why does it matter for API design? Give an example of making a non-idempotent endpoint idempotent.',
    hints: [
      'Idempotent: calling the operation N times has the same effect as calling it once',
      'Non-idempotent example: POST /charge — called twice charges the customer twice if the client retries after a timeout',
      'Fix: client generates a unique idempotency key, sends it in the header. Server deduplicates based on that key',
      'Stripe\'s pattern: cache the response for 24h keyed by idempotency key — same request returns same result',
    ],
    concepts: ['acid-vs-base', 'api-gateway'],
    companies: ['stripe', 'square', 'braintree'],
  },

  // ─── Real Architectures (sd-045–sd-054) ──────────────────────────────────

  {
    id: 'sd-045',
    topic: 'real-architectures',
    difficulty: 'mid',
    prompt: 'Design Twitter\'s tweet feed. How do you serve each user a personalized, real-time timeline?',
    hints: [
      'Fan-out on write for normal users: on tweet, push to each follower\'s feed cache. O(followers) write, O(1) read',
      'Celebrity exception: fan-out on read — pull celebrity tweets at read time, merge with pre-computed feed',
      'Feed cache: Redis sorted set scored by tweet timestamp. Each user has an in-memory feed shard',
      'Real-time delivery: WebSocket or SSE for pushing new tweets to open browser tabs',
    ],
    concepts: ['message-queue-patterns', 'cache-aside-pattern', 'consistent-hashing'],
    companies: ['twitter'],
  },
  {
    id: 'sd-046',
    topic: 'real-architectures',
    difficulty: 'senior',
    prompt: 'Design Discord\'s message delivery system for a server with 50,000 concurrent online members.',
    hints: [
      'Challenge: fanning out a message to 50K clients efficiently — can\'t open 50K connections from one server',
      'Presence gateway: clients connect to regional gateway servers (not app servers). Gateways handle WebSocket connections',
      'Pub/sub backbone: app server publishes to a channel; gateways subscribed to that channel forward to connected clients',
      'Delivery ordering: messages get monotonically increasing snowflake IDs; clients re-order if needed',
    ],
    concepts: ['message-queue-patterns', 'consistent-hashing', 'load-balancing'],
    companies: ['discord'],
  },
  {
    id: 'sd-047',
    topic: 'real-architectures',
    difficulty: 'mid',
    prompt: 'Design Uber\'s ride-matching system. How do you efficiently match riders to nearby drivers?',
    hints: [
      'Geospatial indexing: geohash or S2 cells to bucket drivers by location. Query nearby cells for candidates',
      'Driver location updates: high-frequency writes (every 5s per driver) — use a time-series store, not Postgres',
      'Matching algorithm: find candidates within radius, filter by vehicle type/rating, minimize ETA',
      'Supply/demand imbalance: surge pricing adjusts when drivers < riders in a geohash cell',
    ],
    concepts: ['database-sharding', 'message-queue-patterns'],
    companies: ['uber', 'lyft'],
  },
  {
    id: 'sd-048',
    topic: 'real-architectures',
    difficulty: 'senior',
    prompt: 'Design Netflix\'s video streaming architecture. How does a video get from storage to your browser smoothly?',
    hints: [
      'Adaptive bitrate streaming (HLS/DASH): video encoded at multiple quality levels; player switches based on bandwidth',
      'Content delivery: Netflix Open Connect — ISP-deployed edge servers cache popular content close to viewers',
      'Chunk delivery: player buffers 30-60s ahead. Chunk size trade-off: smaller = more requests, more adaptive; larger = more buffering',
      'Encoding pipeline: original file → multiple resolutions + bitrates → stored in S3 → distributed to edge on demand',
    ],
    concepts: ['cdn-edge-caching', 'load-balancing'],
    companies: ['netflix', 'youtube', 'twitch'],
  },
  {
    id: 'sd-049',
    topic: 'real-architectures',
    difficulty: 'mid',
    prompt: 'Design a URL shortener like bit.ly at 100,000 writes/day and 100 million reads/day.',
    hints: [
      'ID generation: base62-encode a 7-digit counter or random ID. Counter gives sequential IDs (predictable); random avoids guessing',
      'Storage: simple key-value store maps short code → long URL. Reads >> writes → cache aggressively',
      'Redirect: HTTP 301 (permanent, browser caches) vs 302 (temporary, every request hits server — needed for analytics)',
      'Analytics: if you need click tracking, 302 + async write to a click event stream',
    ],
    concepts: ['cache-aside-pattern', 'database-sharding'],
    companies: ['bitly', 'tinyurl'],
  },
  {
    id: 'sd-050',
    topic: 'real-architectures',
    difficulty: 'senior',
    prompt: 'Design a web crawler for building a search index. How do you crawl 1 billion pages efficiently?',
    hints: [
      'URL frontier: priority queue of URLs to crawl. Prioritize by PageRank, freshness, and domain diversity',
      'Politeness: respect robots.txt; rate limit per domain to avoid hammering servers',
      'Deduplication: Bloom filter or URL hash set to avoid recrawling the same page',
      'Distributed crawl: partition URL space by domain hash to dedicated crawler workers — each worker owns a set of domains',
    ],
    concepts: ['bloom-filter', 'consistent-hashing', 'message-queue-patterns'],
    companies: ['google', 'bing', 'commoncrawl'],
  },
  {
    id: 'sd-051',
    topic: 'real-architectures',
    difficulty: 'mid',
    prompt: 'Design a typeahead / autocomplete system for a search box that handles 10,000 requests per second.',
    hints: [
      'Trie in memory: efficient prefix lookup, but building and updating is expensive',
      'Precomputed top-K: for each prefix, store the top 10 completions — fast read, stale on content changes',
      'Cache with short TTL: aggregate query to in-memory cache keyed by prefix. 95% of traffic hits hot prefixes',
      'Locality: build prefix→completions index per language/locale. Don\'t serve English completions to Japanese users',
    ],
    concepts: ['cache-aside-pattern', 'rate-limiting'],
    companies: ['google', 'amazon', 'twitter'],
  },
  {
    id: 'sd-052',
    topic: 'real-architectures',
    difficulty: 'senior',
    prompt: 'Design a distributed payment processing system like Stripe\'s charge flow.',
    hints: [
      'Idempotency keys: client-generated, server deduplicates — prevents double charge on retry',
      'Saga pattern: charge → authorize → capture → settle. Each step has a compensating rollback if later steps fail',
      'Exactly-once guarantee: write "payment_initiated" event before calling card network; only proceed if not already processed',
      'Multi-region: payments can\'t afford availability loss. Active-active with leader-per-customer routing',
    ],
    concepts: ['acid-vs-base', 'consensus-algorithms', 'message-queue-patterns'],
    companies: ['stripe', 'square', 'braintree'],
  },
  {
    id: 'sd-053',
    topic: 'real-architectures',
    difficulty: 'mid',
    prompt: 'Design a Google Docs-style real-time collaborative text editor.',
    hints: [
      'Conflict resolution: Operational Transformation (OT) or CRDT. OT transforms concurrent edits; CRDTs merge automatically',
      'Architecture: CRDT is simpler operationally (no central transform server); OT requires authoritative server',
      'Presence: show where each user\'s cursor is. Lightweight, lossy (last write wins), separate from the document sync channel',
      'Offline support: operations queued locally, replayed against current server state on reconnect',
    ],
    concepts: ['consensus-algorithms', 'message-queue-patterns'],
    companies: ['google', 'notion', 'figma'],
  },
  {
    id: 'sd-054',
    topic: 'real-architectures',
    difficulty: 'senior',
    prompt: 'Design a fraud detection system that can block fraudulent transactions in real time.',
    hints: [
      'Synchronous scoring: rule engine + ML model must return a risk score within 100ms of transaction request',
      'Feature store: precomputed per-user features (recent spend velocity, typical merchants) cached in Redis',
      'Model serving: lightweight gradient boosting or neural net in a sidecar service — not a Python notebook',
      'Feedback loop: flagged transactions reviewed by fraud analysts, labels fed back to retrain model weekly',
    ],
    concepts: ['cache-aside-pattern', 'rate-limiting', 'message-queue-patterns'],
    companies: ['stripe', 'paypal', 'amazon'],
  },

  // ─── Storage + CDN (sd-055–sd-062) ───────────────────────────────────────

  {
    id: 'sd-055',
    topic: 'storage-cdn',
    difficulty: 'junior',
    prompt: 'Design a file upload system that supports files up to 5GB. How do you handle large uploads reliably?',
    hints: [
      'Direct browser → S3 upload with presigned URL — server never handles the bytes, reduces server load and cost',
      'Multipart upload: split into 5-100MB chunks, upload in parallel, reassemble — tolerates network interruption',
      'Progress tracking: client reports chunk completion, server tracks which chunks arrived',
      'Virus scanning: async scan after upload completes; move to public bucket only if clean',
    ],
    concepts: ['cdn-edge-caching'],
    companies: ['dropbox', 'google-drive', 'box'],
  },
  {
    id: 'sd-056',
    topic: 'storage-cdn',
    difficulty: 'mid',
    prompt: 'Design an image processing pipeline that resizes and optimizes user-uploaded images.',
    hints: [
      'On-demand vs pre-compute: resize at request time (Cloudinary model) vs pre-generate all sizes on upload',
      'On-demand is better for unknown dimension requirements; cache resized outputs to avoid repeat computation',
      'Storage: original in S3 (immutable), resized variants cached in CDN with long TTL',
      'Background job queue: process original → generate thumbnails → store variants → mark ready',
    ],
    concepts: ['cdn-edge-caching', 'message-queue-patterns'],
    companies: ['cloudinary', 'imgix', 'instagram'],
  },
  {
    id: 'sd-057',
    topic: 'storage-cdn',
    difficulty: 'mid',
    prompt: 'How does S3 achieve high durability (99.999999999%)? What are the trade-offs?',
    hints: [
      'S3 stores multiple copies across availability zones (typically 3) with erasure coding within each AZ',
      'Eventual consistency: after a PUT, subsequent GETs may return old value until replication completes (now strongly consistent since 2020)',
      'S3 is optimized for large objects and high throughput, not low-latency metadata operations',
      'Cost trade-off: storage is cheap, but request costs add up for high-frequency small reads — consider caching',
    ],
    concepts: ['database-replication', 'cdn-edge-caching'],
    companies: ['amazon', 'cloudflare-r2', 'backblaze'],
  },
  {
    id: 'sd-058',
    topic: 'storage-cdn',
    difficulty: 'senior',
    prompt: 'Design a distributed file system for storing and serving billions of small files (< 1MB each).',
    hints: [
      'Small files challenge: filesystem metadata overhead per file is significant — avoid millions of individual inodes',
      'Haystack (Facebook): pack small files into large container files with an offset index. Single disk seek per read',
      'HDFS is optimized for large files, not small — avoid for this use case',
      'Content-addressable storage: hash-based addressing deduplicates identical files automatically',
    ],
    concepts: ['consistent-hashing', 'database-sharding'],
    companies: ['facebook', 'dropbox', 'backblaze'],
  },
  {
    id: 'sd-059',
    topic: 'storage-cdn',
    difficulty: 'mid',
    prompt: 'Design a CDN purge/invalidation system. How do you ensure old content is evicted quickly after a deploy?',
    hints: [
      'Versioned URLs: /static/main.a1b2c3d.js — no purge needed, new deploy = new hash = new URL. Best for immutable assets',
      'Tag-based purge: tag cache entries with page/section labels; purge by tag on deploy',
      'Surrogate keys (Fastly): associate multiple keys with a response; purge by any key in O(1)',
      'Trade-off: purge-on-deploy is fast but risky (cache cold start); short TTL is simpler but means stale for the TTL window',
    ],
    concepts: ['cdn-edge-caching', 'ttl-and-staleness'],
    companies: ['cloudflare', 'fastly', 'vercel'],
  },
  {
    id: 'sd-060',
    topic: 'storage-cdn',
    difficulty: 'senior',
    prompt: 'Design a backup system for a database that needs RPO < 15 minutes and RTO < 30 minutes.',
    hints: [
      'RPO 15 min: continuous WAL archiving (Postgres WAL to S3) rather than nightly snapshots (RPO = 24h)',
      'RTO 30 min: keep a warm standby replica that is continuously applying WAL — failover by promoting it',
      'Test backups regularly: restore to a test environment weekly. Untested backups frequently fail',
      'Geo-redundancy: backup destination in a different region than primary to survive AZ or regional outage',
    ],
    concepts: ['database-replication', 'consensus-algorithms'],
    companies: ['postgres', 'amazon-rds', 'planetscale'],
  },
  {
    id: 'sd-061',
    topic: 'storage-cdn',
    difficulty: 'mid',
    prompt: 'How would you design a content deduplication system for a file sync service like Dropbox?',
    hints: [
      'Content-addressable storage: SHA-256 hash the file content. Identical files share one physical copy',
      'Block-level deduplication: split file into fixed-size blocks, hash each block — partial file changes only upload changed blocks',
      'Delta sync: compare block hashes between client and server — only upload/download changed blocks',
      'Privacy note: content hashing could theoretically detect if you have a specific file. Encryption before hashing addresses this',
    ],
    concepts: ['bloom-filter'],
    companies: ['dropbox', 'google-drive', 'box'],
  },
  {
    id: 'sd-062',
    topic: 'storage-cdn',
    difficulty: 'junior',
    prompt: 'Design a simple key-value store. What data structures would you use and what operations does it support?',
    hints: [
      'In-memory: hash map for O(1) get/set. LSM tree for persistent storage (RocksDB model)',
      'Operations: GET, SET, DELETE, TTL (expire after N seconds)',
      'TTL implementation: lazy expiry (check on read) + background scan. Avoid eager expiry for performance',
      'Persistence: write-ahead log (WAL) before modifying in-memory state — crash-safe recovery',
    ],
    concepts: ['cache-eviction-policies', 'acid-vs-base'],
    companies: ['redis', 'memcached', 'dynamodb'],
  },

  // ─── Microservices (sd-063–sd-070) ───────────────────────────────────────

  {
    id: 'sd-063',
    topic: 'microservices',
    difficulty: 'mid',
    prompt: 'What problems do microservices solve and what new problems do they introduce?',
    hints: [
      'Benefits: independent deployability, fault isolation, technology flexibility, team autonomy',
      'New problems: distributed tracing (a request spans 5 services — where did it fail?), latency added by network hops',
      'Data consistency: no shared database → distributed transactions required for cross-service operations',
      'Operational overhead: each service needs its own CI/CD, monitoring, scaling, on-call rotation',
    ],
    concepts: ['circuit-breaker', 'service-mesh', 'load-balancing'],
    companies: [],
  },
  {
    id: 'sd-064',
    topic: 'microservices',
    difficulty: 'mid',
    prompt: 'How does a service mesh like Istio improve reliability in a microservices architecture?',
    hints: [
      'Service mesh: sidecar proxies (Envoy) injected alongside each service handle all inbound/outbound traffic',
      'Automatic mTLS between services without code changes — zero-trust network by default',
      'Traffic management: weighted routing for canary deploys, retries, circuit breaking at the proxy level',
      'Observability: automatic distributed traces and metrics from the proxy — no manual instrumentation needed',
    ],
    concepts: ['service-mesh', 'circuit-breaker', 'load-balancing'],
    companies: ['google', 'lyft', 'airbnb'],
  },
  {
    id: 'sd-065',
    topic: 'microservices',
    difficulty: 'senior',
    prompt: 'Design a circuit breaker for a service that makes calls to an unreliable downstream dependency.',
    hints: [
      'States: Closed (normal), Open (stop calling — fast fail), Half-Open (test one request to see if recovered)',
      'Transition to Open: N failures in a sliding window. Transition to Half-Open: after a fixed cooldown',
      'Benefits: prevents cascading failure (your service doesn\'t queue up thousands of waiting threads)',
      'Fallback: when open, serve stale data from cache, return a default, or degrade gracefully',
    ],
    concepts: ['circuit-breaker'],
    companies: ['netflix', 'resilience4j', 'hystrix'],
  },
  {
    id: 'sd-066',
    topic: 'microservices',
    difficulty: 'mid',
    prompt: 'How would you handle service discovery in a dynamic Kubernetes environment?',
    hints: [
      'Kubernetes DNS: services get a stable DNS name (my-service.namespace.svc.cluster.local) automatically',
      'Client-side vs server-side discovery: K8s services do server-side (kube-proxy balances to pods)',
      'Health checking: readiness probe prevents traffic to starting/unhealthy pods; liveness probe restarts stuck pods',
      'External services: CoreDNS can forward specific domains to external resolvers for hybrid cloud setups',
    ],
    concepts: ['load-balancing', 'service-mesh'],
    companies: ['google', 'amazon', 'hashicorp'],
  },
  {
    id: 'sd-067',
    topic: 'microservices',
    difficulty: 'senior',
    prompt: 'Design a distributed tracing system for a microservices architecture with 20 services.',
    hints: [
      'Trace context propagation: each service passes a trace ID + span ID in request headers (W3C TraceContext)',
      'Span: a unit of work within one service. Spans form a parent-child tree representing the request path',
      'Sampling: trace every request at low traffic, sample 1% at high traffic to control storage costs',
      'Storage: Jaeger or Zipkin store traces. Query: find all spans for trace ID, reconstruct the waterfall view',
    ],
    concepts: ['service-mesh', 'api-gateway'],
    companies: ['jaeger', 'datadog', 'honeycomb'],
  },
  {
    id: 'sd-068',
    topic: 'microservices',
    difficulty: 'mid',
    prompt: 'How do you implement a blue-green deployment to release a new version with zero downtime?',
    hints: [
      'Blue-green: maintain two identical environments. Blue is live, green has the new version',
      'Switch: change load balancer to route 100% of traffic from blue to green',
      'Rollback: switch back to blue if issues detected. Blue stays warm during initial green deployment',
      'Database migrations: must be backward-compatible — old blue code must still work against the migrated schema',
    ],
    concepts: ['load-balancing', 'api-gateway'],
    companies: ['netflix', 'amazon', 'heroku'],
  },
  {
    id: 'sd-069',
    topic: 'microservices',
    difficulty: 'senior',
    prompt: 'Design a saga pattern implementation for a multi-step order fulfillment workflow (payment → inventory → shipping).',
    hints: [
      'Choreography saga: each service listens to events and emits events on success/failure — decoupled, hard to track',
      'Orchestration saga: a central orchestrator calls each service and handles rollback — easier to follow, single point',
      'Compensating transactions: if shipping fails, saga runs "release inventory" and "refund payment" compensations',
      'State machine: model the saga as states (PAYMENT_PENDING, PAYMENT_DONE, INVENTORY_RESERVED, ...) for observability',
    ],
    concepts: ['message-queue-patterns', 'acid-vs-base'],
    companies: ['amazon', 'shopify', 'temporal'],
  },
  {
    id: 'sd-070',
    topic: 'microservices',
    difficulty: 'mid',
    prompt: 'How would you implement health checks and graceful shutdown for a microservice under load?',
    hints: [
      'Liveness probe: is the process alive? (simple HTTP 200). Liveness failure → restart the container',
      'Readiness probe: is the service ready to accept traffic? (check DB connection, warm cache). Readiness failure → remove from load balancer',
      'Graceful shutdown: on SIGTERM, stop accepting new requests, finish in-flight requests, then exit (drain period ~30s)',
      'Pre-stop hook in K8s: add a sleep before SIGTERM so load balancer finishes updating routing tables before shutdown begins',
    ],
    concepts: ['load-balancing', 'circuit-breaker'],
    companies: ['google', 'amazon', 'netflix'],
  },
]
