export type Difficulty = 'easy' | 'medium' | 'hard'

export interface NeetcodeProblem {
  slug: string
  title: string
  pattern: string
  difficulty: Difficulty
  url: string
  leetcodeUrl: string
  leetcodePremium?: true
}

export const PATTERNS = [
  'Arrays & Hashing',
  'Two Pointers',
  'Sliding Window',
  'Stack',
  'Binary Search',
  'Linked List',
  'Trees',
  'Heap / Priority Queue',
  'Backtracking',
  'Tries',
  'Graphs',
  'Advanced Graphs',
  '1D Dynamic Programming',
  '2D Dynamic Programming',
  'Greedy',
  'Intervals',
  'Math & Geometry',
  'Bit Manipulation',
] as const

export type Pattern = (typeof PATTERNS)[number]
export type DsaTrack = '75' | '150' | '250'

export const NEETCODE_150: NeetcodeProblem[] = [
  // Arrays & Hashing (9)
  { slug: 'duplicate-integer',             title: 'Contains Duplicate',                             pattern: 'Arrays & Hashing',        difficulty: 'easy',   url: 'https://neetcode.io/problems/duplicate-integer',             leetcodeUrl: 'https://leetcode.com/problems/contains-duplicate/' },
  { slug: 'valid-anagram',                 title: 'Valid Anagram',                                  pattern: 'Arrays & Hashing',        difficulty: 'easy',   url: 'https://neetcode.io/problems/valid-anagram',                 leetcodeUrl: 'https://leetcode.com/problems/valid-anagram/' },
  { slug: 'two-sum',                       title: 'Two Sum',                                        pattern: 'Arrays & Hashing',        difficulty: 'easy',   url: 'https://neetcode.io/problems/two-sum',                       leetcodeUrl: 'https://leetcode.com/problems/two-sum/' },
  { slug: 'anagram-groups',               title: 'Group Anagrams',                                  pattern: 'Arrays & Hashing',        difficulty: 'medium', url: 'https://neetcode.io/problems/anagram-groups',               leetcodeUrl: 'https://leetcode.com/problems/group-anagrams/' },
  { slug: 'top-k-elements-in-list',       title: 'Top K Frequent Elements',                         pattern: 'Arrays & Hashing',        difficulty: 'medium', url: 'https://neetcode.io/problems/top-k-elements-in-list',       leetcodeUrl: 'https://leetcode.com/problems/top-k-frequent-elements/' },
  { slug: 'products-of-array-discluding-self', title: 'Product of Array Except Self',              pattern: 'Arrays & Hashing',        difficulty: 'medium', url: 'https://neetcode.io/problems/products-of-array-discluding-self', leetcodeUrl: 'https://leetcode.com/problems/product-of-array-except-self/' },
  { slug: 'valid-sudoku',                  title: 'Valid Sudoku',                                   pattern: 'Arrays & Hashing',        difficulty: 'medium', url: 'https://neetcode.io/problems/valid-sudoku',                  leetcodeUrl: 'https://leetcode.com/problems/valid-sudoku/' },
  { slug: 'string-encode-and-decode',     title: 'Encode and Decode Strings',                       pattern: 'Arrays & Hashing',        difficulty: 'medium', url: 'https://neetcode.io/problems/string-encode-and-decode',     leetcodeUrl: 'https://leetcode.com/problems/encode-and-decode-strings/', leetcodePremium: true },
  { slug: 'longest-consecutive-sequence', title: 'Longest Consecutive Sequence',                    pattern: 'Arrays & Hashing',        difficulty: 'medium', url: 'https://neetcode.io/problems/longest-consecutive-sequence', leetcodeUrl: 'https://leetcode.com/problems/longest-consecutive-sequence/' },

  // Two Pointers (5)
  { slug: 'is-palindrome',                title: 'Valid Palindrome',                                pattern: 'Two Pointers',            difficulty: 'easy',   url: 'https://neetcode.io/problems/is-palindrome',                leetcodeUrl: 'https://leetcode.com/problems/valid-palindrome/' },
  { slug: 'two-integer-sum-ii',           title: 'Two Sum II - Input Array Is Sorted',              pattern: 'Two Pointers',            difficulty: 'medium', url: 'https://neetcode.io/problems/two-integer-sum-ii',           leetcodeUrl: 'https://leetcode.com/problems/two-sum-ii-input-array-is-sorted/' },
  { slug: 'three-integer-sum',            title: '3Sum',                                            pattern: 'Two Pointers',            difficulty: 'medium', url: 'https://neetcode.io/problems/three-integer-sum',            leetcodeUrl: 'https://leetcode.com/problems/3sum/' },
  { slug: 'max-water-container',          title: 'Container With Most Water',                       pattern: 'Two Pointers',            difficulty: 'medium', url: 'https://neetcode.io/problems/max-water-container',          leetcodeUrl: 'https://leetcode.com/problems/container-with-most-water/' },
  { slug: 'trapping-rain-water',          title: 'Trapping Rain Water',                             pattern: 'Two Pointers',            difficulty: 'hard',   url: 'https://neetcode.io/problems/trapping-rain-water',          leetcodeUrl: 'https://leetcode.com/problems/trapping-rain-water/' },

  // Sliding Window (6)
  { slug: 'buy-and-sell-crypto',          title: 'Best Time to Buy and Sell Stock',                 pattern: 'Sliding Window',          difficulty: 'easy',   url: 'https://neetcode.io/problems/buy-and-sell-crypto',          leetcodeUrl: 'https://leetcode.com/problems/best-time-to-buy-and-sell-stock/' },
  { slug: 'longest-substring-without-duplicates', title: 'Longest Substring Without Repeating Characters', pattern: 'Sliding Window', difficulty: 'medium', url: 'https://neetcode.io/problems/longest-substring-without-duplicates', leetcodeUrl: 'https://leetcode.com/problems/longest-substring-without-repeating-characters/' },
  { slug: 'longest-repeating-substring-with-replacement', title: 'Longest Repeating Character Replacement', pattern: 'Sliding Window', difficulty: 'medium', url: 'https://neetcode.io/problems/longest-repeating-substring-with-replacement', leetcodeUrl: 'https://leetcode.com/problems/longest-repeating-character-replacement/' },
  { slug: 'permutation-string',           title: 'Permutation in String',                           pattern: 'Sliding Window',          difficulty: 'medium', url: 'https://neetcode.io/problems/permutation-string',           leetcodeUrl: 'https://leetcode.com/problems/permutation-in-string/' },
  { slug: 'minimum-window-with-characters', title: 'Minimum Window Substring',                     pattern: 'Sliding Window',          difficulty: 'hard',   url: 'https://neetcode.io/problems/minimum-window-with-characters', leetcodeUrl: 'https://leetcode.com/problems/minimum-window-substring/' },
  { slug: 'sliding-window-maximum',       title: 'Sliding Window Maximum',                          pattern: 'Sliding Window',          difficulty: 'hard',   url: 'https://neetcode.io/problems/sliding-window-maximum',       leetcodeUrl: 'https://leetcode.com/problems/sliding-window-maximum/' },

  // Stack (7)
  { slug: 'validate-parentheses',         title: 'Valid Parentheses',                               pattern: 'Stack',                   difficulty: 'easy',   url: 'https://neetcode.io/problems/validate-parentheses',         leetcodeUrl: 'https://leetcode.com/problems/valid-parentheses/' },
  { slug: 'minimum-stack',                title: 'Min Stack',                                       pattern: 'Stack',                   difficulty: 'medium', url: 'https://neetcode.io/problems/minimum-stack',                leetcodeUrl: 'https://leetcode.com/problems/min-stack/' },
  { slug: 'evaluate-reverse-polish-notation', title: 'Evaluate Reverse Polish Notation',           pattern: 'Stack',                   difficulty: 'medium', url: 'https://neetcode.io/problems/evaluate-reverse-polish-notation', leetcodeUrl: 'https://leetcode.com/problems/evaluate-reverse-polish-notation/' },
  { slug: 'generate-parentheses',         title: 'Generate Parentheses',                            pattern: 'Stack',                   difficulty: 'medium', url: 'https://neetcode.io/problems/generate-parentheses',         leetcodeUrl: 'https://leetcode.com/problems/generate-parentheses/' },
  { slug: 'daily-temperatures',           title: 'Daily Temperatures',                              pattern: 'Stack',                   difficulty: 'medium', url: 'https://neetcode.io/problems/daily-temperatures',           leetcodeUrl: 'https://leetcode.com/problems/daily-temperatures/' },
  { slug: 'car-fleet',                    title: 'Car Fleet',                                       pattern: 'Stack',                   difficulty: 'medium', url: 'https://neetcode.io/problems/car-fleet',                    leetcodeUrl: 'https://leetcode.com/problems/car-fleet/' },
  { slug: 'largest-rectangle-in-histogram', title: 'Largest Rectangle in Histogram',               pattern: 'Stack',                   difficulty: 'hard',   url: 'https://neetcode.io/problems/largest-rectangle-in-histogram', leetcodeUrl: 'https://leetcode.com/problems/largest-rectangle-in-histogram/' },

  // Binary Search (7)
  { slug: 'binary-search',                title: 'Binary Search',                                   pattern: 'Binary Search',           difficulty: 'easy',   url: 'https://neetcode.io/problems/binary-search',                leetcodeUrl: 'https://leetcode.com/problems/binary-search/' },
  { slug: 'search-2d-matrix',             title: 'Search a 2D Matrix',                              pattern: 'Binary Search',           difficulty: 'medium', url: 'https://neetcode.io/problems/search-2d-matrix',             leetcodeUrl: 'https://leetcode.com/problems/search-a-2d-matrix/' },
  { slug: 'eating-bananas',               title: 'Koko Eating Bananas',                             pattern: 'Binary Search',           difficulty: 'medium', url: 'https://neetcode.io/problems/eating-bananas',               leetcodeUrl: 'https://leetcode.com/problems/koko-eating-bananas/' },
  { slug: 'find-minimum-in-rotated-sorted-array', title: 'Find Minimum in Rotated Sorted Array',   pattern: 'Binary Search',           difficulty: 'medium', url: 'https://neetcode.io/problems/find-minimum-in-rotated-sorted-array', leetcodeUrl: 'https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/' },
  { slug: 'find-target-in-rotated-sorted-array', title: 'Search in Rotated Sorted Array',          pattern: 'Binary Search',           difficulty: 'medium', url: 'https://neetcode.io/problems/find-target-in-rotated-sorted-array', leetcodeUrl: 'https://leetcode.com/problems/search-in-rotated-sorted-array/' },
  { slug: 'time-based-key-value-store',   title: 'Time Based Key-Value Store',                      pattern: 'Binary Search',           difficulty: 'medium', url: 'https://neetcode.io/problems/time-based-key-value-store',   leetcodeUrl: 'https://leetcode.com/problems/time-based-key-value-store/' },
  { slug: 'median-of-two-sorted-arrays',  title: 'Median of Two Sorted Arrays',                     pattern: 'Binary Search',           difficulty: 'hard',   url: 'https://neetcode.io/problems/median-of-two-sorted-arrays',  leetcodeUrl: 'https://leetcode.com/problems/median-of-two-sorted-arrays/' },

  // Linked List (11)
  { slug: 'reverse-a-linked-list',        title: 'Reverse Linked List',                             pattern: 'Linked List',             difficulty: 'easy',   url: 'https://neetcode.io/problems/reverse-a-linked-list',        leetcodeUrl: 'https://leetcode.com/problems/reverse-linked-list/' },
  { slug: 'merge-two-sorted-linked-lists', title: 'Merge Two Sorted Lists',                        pattern: 'Linked List',             difficulty: 'easy',   url: 'https://neetcode.io/problems/merge-two-sorted-linked-lists', leetcodeUrl: 'https://leetcode.com/problems/merge-two-sorted-lists/' },
  { slug: 'reorder-linked-list',          title: 'Reorder List',                                    pattern: 'Linked List',             difficulty: 'medium', url: 'https://neetcode.io/problems/reorder-linked-list',          leetcodeUrl: 'https://leetcode.com/problems/reorder-list/' },
  { slug: 'remove-node-from-end-of-linked-list', title: 'Remove Nth Node From End of List',        pattern: 'Linked List',             difficulty: 'medium', url: 'https://neetcode.io/problems/remove-node-from-end-of-linked-list', leetcodeUrl: 'https://leetcode.com/problems/remove-nth-node-from-end-of-list/' },
  { slug: 'copy-linked-list-with-random-pointer', title: 'Copy List with Random Pointer',          pattern: 'Linked List',             difficulty: 'medium', url: 'https://neetcode.io/problems/copy-linked-list-with-random-pointer', leetcodeUrl: 'https://leetcode.com/problems/copy-list-with-random-pointer/' },
  { slug: 'add-two-numbers',              title: 'Add Two Numbers',                                 pattern: 'Linked List',             difficulty: 'medium', url: 'https://neetcode.io/problems/add-two-numbers',              leetcodeUrl: 'https://leetcode.com/problems/add-two-numbers/' },
  { slug: 'linked-list-cycle-detection',  title: 'Linked List Cycle',                               pattern: 'Linked List',             difficulty: 'easy',   url: 'https://neetcode.io/problems/linked-list-cycle-detection',  leetcodeUrl: 'https://leetcode.com/problems/linked-list-cycle/' },
  { slug: 'find-duplicate-integer',       title: 'Find the Duplicate Number',                       pattern: 'Linked List',             difficulty: 'medium', url: 'https://neetcode.io/problems/find-duplicate-integer',       leetcodeUrl: 'https://leetcode.com/problems/find-the-duplicate-number/' },
  { slug: 'lru-cache',                    title: 'LRU Cache',                                       pattern: 'Linked List',             difficulty: 'medium', url: 'https://neetcode.io/problems/lru-cache',                    leetcodeUrl: 'https://leetcode.com/problems/lru-cache/' },
  { slug: 'merge-k-sorted-linked-lists',  title: 'Merge K Sorted Lists',                            pattern: 'Linked List',             difficulty: 'hard',   url: 'https://neetcode.io/problems/merge-k-sorted-linked-lists',  leetcodeUrl: 'https://leetcode.com/problems/merge-k-sorted-lists/' },
  { slug: 'reverse-nodes-in-k-group',     title: 'Reverse Nodes in K-Group',                        pattern: 'Linked List',             difficulty: 'hard',   url: 'https://neetcode.io/problems/reverse-nodes-in-k-group',     leetcodeUrl: 'https://leetcode.com/problems/reverse-nodes-in-k-group/' },

  // Trees (15)
  { slug: 'invert-a-binary-tree',         title: 'Invert Binary Tree',                              pattern: 'Trees',                   difficulty: 'easy',   url: 'https://neetcode.io/problems/invert-a-binary-tree',         leetcodeUrl: 'https://leetcode.com/problems/invert-binary-tree/' },
  { slug: 'depth-of-binary-tree',         title: 'Maximum Depth of Binary Tree',                    pattern: 'Trees',                   difficulty: 'easy',   url: 'https://neetcode.io/problems/depth-of-binary-tree',         leetcodeUrl: 'https://leetcode.com/problems/maximum-depth-of-binary-tree/' },
  { slug: 'binary-tree-diameter',         title: 'Diameter of Binary Tree',                         pattern: 'Trees',                   difficulty: 'easy',   url: 'https://neetcode.io/problems/binary-tree-diameter',         leetcodeUrl: 'https://leetcode.com/problems/diameter-of-binary-tree/' },
  { slug: 'balanced-binary-tree',         title: 'Balanced Binary Tree',                            pattern: 'Trees',                   difficulty: 'easy',   url: 'https://neetcode.io/problems/balanced-binary-tree',         leetcodeUrl: 'https://leetcode.com/problems/balanced-binary-tree/' },
  { slug: 'same-binary-tree',             title: 'Same Tree',                                       pattern: 'Trees',                   difficulty: 'easy',   url: 'https://neetcode.io/problems/same-binary-tree',             leetcodeUrl: 'https://leetcode.com/problems/same-tree/' },
  { slug: 'subtree-of-a-binary-tree',     title: 'Subtree of Another Tree',                         pattern: 'Trees',                   difficulty: 'easy',   url: 'https://neetcode.io/problems/subtree-of-a-binary-tree',     leetcodeUrl: 'https://leetcode.com/problems/subtree-of-another-tree/' },
  { slug: 'lowest-common-ancestor-in-binary-search-tree', title: 'Lowest Common Ancestor of a BST', pattern: 'Trees',                  difficulty: 'medium', url: 'https://neetcode.io/problems/lowest-common-ancestor-in-binary-search-tree', leetcodeUrl: 'https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/' },
  { slug: 'level-order-traversal-of-binary-tree', title: 'Binary Tree Level Order Traversal',       pattern: 'Trees',                   difficulty: 'medium', url: 'https://neetcode.io/problems/level-order-traversal-of-binary-tree', leetcodeUrl: 'https://leetcode.com/problems/binary-tree-level-order-traversal/' },
  { slug: 'binary-tree-right-side-view',  title: 'Binary Tree Right Side View',                     pattern: 'Trees',                   difficulty: 'medium', url: 'https://neetcode.io/problems/binary-tree-right-side-view',  leetcodeUrl: 'https://leetcode.com/problems/binary-tree-right-side-view/' },
  { slug: 'count-good-nodes-in-binary-tree', title: 'Count Good Nodes in Binary Tree',              pattern: 'Trees',                   difficulty: 'medium', url: 'https://neetcode.io/problems/count-good-nodes-in-binary-tree', leetcodeUrl: 'https://leetcode.com/problems/count-good-nodes-in-binary-tree/' },
  { slug: 'valid-binary-search-tree',     title: 'Validate Binary Search Tree',                     pattern: 'Trees',                   difficulty: 'medium', url: 'https://neetcode.io/problems/valid-binary-search-tree',     leetcodeUrl: 'https://leetcode.com/problems/validate-binary-search-tree/' },
  { slug: 'kth-smallest-integer-in-bst',  title: 'Kth Smallest Element in a BST',                   pattern: 'Trees',                   difficulty: 'medium', url: 'https://neetcode.io/problems/kth-smallest-integer-in-bst',  leetcodeUrl: 'https://leetcode.com/problems/kth-smallest-element-in-a-bst/' },
  { slug: 'binary-tree-from-preorder-and-inorder-traversal', title: 'Construct Binary Tree from Preorder and Inorder Traversal', pattern: 'Trees', difficulty: 'medium', url: 'https://neetcode.io/problems/binary-tree-from-preorder-and-inorder-traversal', leetcodeUrl: 'https://leetcode.com/problems/construct-binary-tree-from-preorder-and-inorder-traversal/' },
  { slug: 'binary-tree-maximum-path-sum', title: 'Binary Tree Maximum Path Sum',                    pattern: 'Trees',                   difficulty: 'hard',   url: 'https://neetcode.io/problems/binary-tree-maximum-path-sum', leetcodeUrl: 'https://leetcode.com/problems/binary-tree-maximum-path-sum/' },
  { slug: 'serialize-and-deserialize-binary-tree', title: 'Serialize and Deserialize Binary Tree',  pattern: 'Trees',                   difficulty: 'hard',   url: 'https://neetcode.io/problems/serialize-and-deserialize-binary-tree', leetcodeUrl: 'https://leetcode.com/problems/serialize-and-deserialize-binary-tree/' },

  // Heap / Priority Queue (7)
  { slug: 'kth-largest-integer-in-a-stream', title: 'Kth Largest Element in a Stream',             pattern: 'Heap / Priority Queue',   difficulty: 'easy',   url: 'https://neetcode.io/problems/kth-largest-integer-in-a-stream', leetcodeUrl: 'https://leetcode.com/problems/kth-largest-element-in-a-stream/' },
  { slug: 'last-stone-weight',            title: 'Last Stone Weight',                               pattern: 'Heap / Priority Queue',   difficulty: 'easy',   url: 'https://neetcode.io/problems/last-stone-weight',            leetcodeUrl: 'https://leetcode.com/problems/last-stone-weight/' },
  { slug: 'k-closest-points-to-origin',   title: 'K Closest Points to Origin',                      pattern: 'Heap / Priority Queue',   difficulty: 'medium', url: 'https://neetcode.io/problems/k-closest-points-to-origin',   leetcodeUrl: 'https://leetcode.com/problems/k-closest-points-to-origin/' },
  { slug: 'kth-largest-element-in-an-array', title: 'Kth Largest Element in an Array',             pattern: 'Heap / Priority Queue',   difficulty: 'medium', url: 'https://neetcode.io/problems/kth-largest-element-in-an-array', leetcodeUrl: 'https://leetcode.com/problems/kth-largest-element-in-an-array/' },
  { slug: 'task-scheduling',              title: 'Task Scheduler',                                  pattern: 'Heap / Priority Queue',   difficulty: 'medium', url: 'https://neetcode.io/problems/task-scheduling',              leetcodeUrl: 'https://leetcode.com/problems/task-scheduler/' },
  { slug: 'design-twitter-feed',          title: 'Design Twitter',                                  pattern: 'Heap / Priority Queue',   difficulty: 'medium', url: 'https://neetcode.io/problems/design-twitter-feed',          leetcodeUrl: 'https://leetcode.com/problems/design-twitter/' },
  { slug: 'find-median-in-a-data-stream', title: 'Find Median from Data Stream',                    pattern: 'Heap / Priority Queue',   difficulty: 'hard',   url: 'https://neetcode.io/problems/find-median-in-a-data-stream', leetcodeUrl: 'https://leetcode.com/problems/find-median-from-data-stream/' },

  // Backtracking (9)
  { slug: 'subsets',                      title: 'Subsets',                                         pattern: 'Backtracking',            difficulty: 'medium', url: 'https://neetcode.io/problems/subsets',                      leetcodeUrl: 'https://leetcode.com/problems/subsets/' },
  { slug: 'combination-target-sum',       title: 'Combination Sum',                                 pattern: 'Backtracking',            difficulty: 'medium', url: 'https://neetcode.io/problems/combination-target-sum',       leetcodeUrl: 'https://leetcode.com/problems/combination-sum/' },
  { slug: 'permutations',                 title: 'Permutations',                                    pattern: 'Backtracking',            difficulty: 'medium', url: 'https://neetcode.io/problems/permutations',                 leetcodeUrl: 'https://leetcode.com/problems/permutations/' },
  { slug: 'subsets-ii',                   title: 'Subsets II',                                      pattern: 'Backtracking',            difficulty: 'medium', url: 'https://neetcode.io/problems/subsets-ii',                   leetcodeUrl: 'https://leetcode.com/problems/subsets-ii/' },
  { slug: 'combination-sum-ii',           title: 'Combination Sum II',                              pattern: 'Backtracking',            difficulty: 'medium', url: 'https://neetcode.io/problems/combination-sum-ii',           leetcodeUrl: 'https://leetcode.com/problems/combination-sum-ii/' },
  { slug: 'search-for-word',              title: 'Word Search',                                     pattern: 'Backtracking',            difficulty: 'medium', url: 'https://neetcode.io/problems/search-for-word',              leetcodeUrl: 'https://leetcode.com/problems/word-search/' },
  { slug: 'palindrome-partitioning',      title: 'Palindrome Partitioning',                         pattern: 'Backtracking',            difficulty: 'medium', url: 'https://neetcode.io/problems/palindrome-partitioning',      leetcodeUrl: 'https://leetcode.com/problems/palindrome-partitioning/' },
  { slug: 'combinations-of-a-phone-number', title: 'Letter Combinations of a Phone Number',        pattern: 'Backtracking',            difficulty: 'medium', url: 'https://neetcode.io/problems/combinations-of-a-phone-number', leetcodeUrl: 'https://leetcode.com/problems/letter-combinations-of-a-phone-number/' },
  { slug: 'n-queens',                     title: 'N-Queens',                                        pattern: 'Backtracking',            difficulty: 'hard',   url: 'https://neetcode.io/problems/n-queens',                     leetcodeUrl: 'https://leetcode.com/problems/n-queens/' },

  // Tries (3)
  { slug: 'implement-prefix-tree',        title: 'Implement Trie (Prefix Tree)',                    pattern: 'Tries',                   difficulty: 'medium', url: 'https://neetcode.io/problems/implement-prefix-tree',        leetcodeUrl: 'https://leetcode.com/problems/implement-trie-prefix-tree/' },
  { slug: 'design-word-search-data-structure', title: 'Design Add and Search Words Data Structure', pattern: 'Tries',                  difficulty: 'medium', url: 'https://neetcode.io/problems/design-word-search-data-structure', leetcodeUrl: 'https://leetcode.com/problems/design-add-and-search-words-data-structure/' },
  { slug: 'search-for-word-ii',           title: 'Word Search II',                                  pattern: 'Tries',                   difficulty: 'hard',   url: 'https://neetcode.io/problems/search-for-word-ii',           leetcodeUrl: 'https://leetcode.com/problems/word-search-ii/' },

  // Graphs (13)
  { slug: 'count-number-of-islands',      title: 'Number of Islands',                               pattern: 'Graphs',                  difficulty: 'medium', url: 'https://neetcode.io/problems/count-number-of-islands',      leetcodeUrl: 'https://leetcode.com/problems/number-of-islands/' },
  { slug: 'max-area-of-island',           title: 'Max Area of Island',                              pattern: 'Graphs',                  difficulty: 'medium', url: 'https://neetcode.io/problems/max-area-of-island',           leetcodeUrl: 'https://leetcode.com/problems/max-area-of-island/' },
  { slug: 'clone-graph',                  title: 'Clone Graph',                                     pattern: 'Graphs',                  difficulty: 'medium', url: 'https://neetcode.io/problems/clone-graph',                  leetcodeUrl: 'https://leetcode.com/problems/clone-graph/' },
  { slug: 'islands-and-treasure',         title: 'Walls and Gates',                                 pattern: 'Graphs',                  difficulty: 'medium', url: 'https://neetcode.io/problems/islands-and-treasure',         leetcodeUrl: 'https://leetcode.com/problems/walls-and-gates/', leetcodePremium: true },
  { slug: 'rotting-fruit',                title: 'Rotting Oranges',                                 pattern: 'Graphs',                  difficulty: 'medium', url: 'https://neetcode.io/problems/rotting-fruit',                leetcodeUrl: 'https://leetcode.com/problems/rotting-oranges/' },
  { slug: 'pacific-atlantic-water-flow',  title: 'Pacific Atlantic Water Flow',                     pattern: 'Graphs',                  difficulty: 'medium', url: 'https://neetcode.io/problems/pacific-atlantic-water-flow',  leetcodeUrl: 'https://leetcode.com/problems/pacific-atlantic-water-flow/' },
  { slug: 'surrounded-regions',           title: 'Surrounded Regions',                              pattern: 'Graphs',                  difficulty: 'medium', url: 'https://neetcode.io/problems/surrounded-regions',           leetcodeUrl: 'https://leetcode.com/problems/surrounded-regions/' },
  { slug: 'course-schedule',              title: 'Course Schedule',                                 pattern: 'Graphs',                  difficulty: 'medium', url: 'https://neetcode.io/problems/course-schedule',              leetcodeUrl: 'https://leetcode.com/problems/course-schedule/' },
  { slug: 'course-schedule-ii',           title: 'Course Schedule II',                              pattern: 'Graphs',                  difficulty: 'medium', url: 'https://neetcode.io/problems/course-schedule-ii',           leetcodeUrl: 'https://leetcode.com/problems/course-schedule-ii/' },
  { slug: 'valid-tree',                   title: 'Graph Valid Tree',                                pattern: 'Graphs',                  difficulty: 'medium', url: 'https://neetcode.io/problems/valid-tree',                   leetcodeUrl: 'https://leetcode.com/problems/graph-valid-tree/', leetcodePremium: true },
  { slug: 'count-connected-components',   title: 'Number of Connected Components in an Undirected Graph', pattern: 'Graphs',           difficulty: 'medium', url: 'https://neetcode.io/problems/count-connected-components',   leetcodeUrl: 'https://leetcode.com/problems/number-of-connected-components-in-an-undirected-graph/', leetcodePremium: true },
  { slug: 'redundant-connection',         title: 'Redundant Connection',                            pattern: 'Graphs',                  difficulty: 'medium', url: 'https://neetcode.io/problems/redundant-connection',         leetcodeUrl: 'https://leetcode.com/problems/redundant-connection/' },
  { slug: 'word-ladder',                  title: 'Word Ladder',                                     pattern: 'Graphs',                  difficulty: 'hard',   url: 'https://neetcode.io/problems/word-ladder',                  leetcodeUrl: 'https://leetcode.com/problems/word-ladder/' },

  // Advanced Graphs (6)
  { slug: 'reconstruct-flight-path',      title: 'Reconstruct Itinerary',                           pattern: 'Advanced Graphs',         difficulty: 'hard',   url: 'https://neetcode.io/problems/reconstruct-flight-path',      leetcodeUrl: 'https://leetcode.com/problems/reconstruct-itinerary/' },
  { slug: 'min-cost-to-connect-points',   title: 'Min Cost to Connect All Points',                  pattern: 'Advanced Graphs',         difficulty: 'medium', url: 'https://neetcode.io/problems/min-cost-to-connect-points',   leetcodeUrl: 'https://leetcode.com/problems/min-cost-to-connect-all-points/' },
  { slug: 'network-delay-time',           title: 'Network Delay Time',                              pattern: 'Advanced Graphs',         difficulty: 'medium', url: 'https://neetcode.io/problems/network-delay-time',           leetcodeUrl: 'https://leetcode.com/problems/network-delay-time/' },
  { slug: 'swim-in-rising-water',         title: 'Swim in Rising Water',                            pattern: 'Advanced Graphs',         difficulty: 'hard',   url: 'https://neetcode.io/problems/swim-in-rising-water',         leetcodeUrl: 'https://leetcode.com/problems/swim-in-rising-water/' },
  { slug: 'foreign-dictionary',           title: 'Alien Dictionary',                                pattern: 'Advanced Graphs',         difficulty: 'hard',   url: 'https://neetcode.io/problems/foreign-dictionary',           leetcodeUrl: 'https://leetcode.com/problems/alien-dictionary/', leetcodePremium: true },
  { slug: 'cheapest-flight-path',         title: 'Cheapest Flights Within K Stops',                 pattern: 'Advanced Graphs',         difficulty: 'medium', url: 'https://neetcode.io/problems/cheapest-flight-path',         leetcodeUrl: 'https://leetcode.com/problems/cheapest-flights-within-k-stops/' },

  // 1D Dynamic Programming (12)
  { slug: 'climbing-stairs',              title: 'Climbing Stairs',                                 pattern: '1D Dynamic Programming',  difficulty: 'easy',   url: 'https://neetcode.io/problems/climbing-stairs',              leetcodeUrl: 'https://leetcode.com/problems/climbing-stairs/' },
  { slug: 'min-cost-climbing-stairs',     title: 'Min Cost Climbing Stairs',                        pattern: '1D Dynamic Programming',  difficulty: 'easy',   url: 'https://neetcode.io/problems/min-cost-climbing-stairs',     leetcodeUrl: 'https://leetcode.com/problems/min-cost-climbing-stairs/' },
  { slug: 'house-robber',                 title: 'House Robber',                                    pattern: '1D Dynamic Programming',  difficulty: 'medium', url: 'https://neetcode.io/problems/house-robber',                 leetcodeUrl: 'https://leetcode.com/problems/house-robber/' },
  { slug: 'house-robber-ii',              title: 'House Robber II',                                 pattern: '1D Dynamic Programming',  difficulty: 'medium', url: 'https://neetcode.io/problems/house-robber-ii',              leetcodeUrl: 'https://leetcode.com/problems/house-robber-ii/' },
  { slug: 'longest-palindromic-substring', title: 'Longest Palindromic Substring',                 pattern: '1D Dynamic Programming',  difficulty: 'medium', url: 'https://neetcode.io/problems/longest-palindromic-substring', leetcodeUrl: 'https://leetcode.com/problems/longest-palindromic-substring/' },
  { slug: 'palindromic-substrings',       title: 'Palindromic Substrings',                          pattern: '1D Dynamic Programming',  difficulty: 'medium', url: 'https://neetcode.io/problems/palindromic-substrings',       leetcodeUrl: 'https://leetcode.com/problems/palindromic-substrings/' },
  { slug: 'decode-ways',                  title: 'Decode Ways',                                     pattern: '1D Dynamic Programming',  difficulty: 'medium', url: 'https://neetcode.io/problems/decode-ways',                  leetcodeUrl: 'https://leetcode.com/problems/decode-ways/' },
  { slug: 'coin-change',                  title: 'Coin Change',                                     pattern: '1D Dynamic Programming',  difficulty: 'medium', url: 'https://neetcode.io/problems/coin-change',                  leetcodeUrl: 'https://leetcode.com/problems/coin-change/' },
  { slug: 'maximum-product-subarray',     title: 'Maximum Product Subarray',                        pattern: '1D Dynamic Programming',  difficulty: 'medium', url: 'https://neetcode.io/problems/maximum-product-subarray',     leetcodeUrl: 'https://leetcode.com/problems/maximum-product-subarray/' },
  { slug: 'word-break',                   title: 'Word Break',                                      pattern: '1D Dynamic Programming',  difficulty: 'medium', url: 'https://neetcode.io/problems/word-break',                   leetcodeUrl: 'https://leetcode.com/problems/word-break/' },
  { slug: 'longest-increasing-subsequence', title: 'Longest Increasing Subsequence',               pattern: '1D Dynamic Programming',  difficulty: 'medium', url: 'https://neetcode.io/problems/longest-increasing-subsequence', leetcodeUrl: 'https://leetcode.com/problems/longest-increasing-subsequence/' },
  { slug: 'partition-equal-subset-sum',   title: 'Partition Equal Subset Sum',                      pattern: '1D Dynamic Programming',  difficulty: 'medium', url: 'https://neetcode.io/problems/partition-equal-subset-sum',   leetcodeUrl: 'https://leetcode.com/problems/partition-equal-subset-sum/' },

  // 2D Dynamic Programming (11)
  { slug: 'count-paths',                  title: 'Unique Paths',                                    pattern: '2D Dynamic Programming',  difficulty: 'medium', url: 'https://neetcode.io/problems/count-paths',                  leetcodeUrl: 'https://leetcode.com/problems/unique-paths/' },
  { slug: 'longest-common-subsequence',   title: 'Longest Common Subsequence',                      pattern: '2D Dynamic Programming',  difficulty: 'medium', url: 'https://neetcode.io/problems/longest-common-subsequence',   leetcodeUrl: 'https://leetcode.com/problems/longest-common-subsequence/' },
  { slug: 'buy-and-sell-stock-with-cooldown', title: 'Best Time to Buy and Sell Stock with Cooldown', pattern: '2D Dynamic Programming', difficulty: 'medium', url: 'https://neetcode.io/problems/buy-and-sell-stock-with-cooldown', leetcodeUrl: 'https://leetcode.com/problems/best-time-to-buy-and-sell-stock-with-cooldown/' },
  { slug: 'coin-change-ii',               title: 'Coin Change II',                                  pattern: '2D Dynamic Programming',  difficulty: 'medium', url: 'https://neetcode.io/problems/coin-change-ii',               leetcodeUrl: 'https://leetcode.com/problems/coin-change-ii/' },
  { slug: 'target-sum',                   title: 'Target Sum',                                      pattern: '2D Dynamic Programming',  difficulty: 'medium', url: 'https://neetcode.io/problems/target-sum',                   leetcodeUrl: 'https://leetcode.com/problems/target-sum/' },
  { slug: 'interleaving-string',          title: 'Interleaving String',                             pattern: '2D Dynamic Programming',  difficulty: 'medium', url: 'https://neetcode.io/problems/interleaving-string',          leetcodeUrl: 'https://leetcode.com/problems/interleaving-string/' },
  { slug: 'longest-increasing-path-in-matrix', title: 'Longest Increasing Path in a Matrix',       pattern: '2D Dynamic Programming',  difficulty: 'hard',   url: 'https://neetcode.io/problems/longest-increasing-path-in-matrix', leetcodeUrl: 'https://leetcode.com/problems/longest-increasing-path-in-a-matrix/' },
  { slug: 'distinct-subsequences',        title: 'Distinct Subsequences',                           pattern: '2D Dynamic Programming',  difficulty: 'hard',   url: 'https://neetcode.io/problems/distinct-subsequences',        leetcodeUrl: 'https://leetcode.com/problems/distinct-subsequences/' },
  { slug: 'edit-distance',                title: 'Edit Distance',                                   pattern: '2D Dynamic Programming',  difficulty: 'medium', url: 'https://neetcode.io/problems/edit-distance',                leetcodeUrl: 'https://leetcode.com/problems/edit-distance/' },
  { slug: 'burst-balloons',               title: 'Burst Balloons',                                  pattern: '2D Dynamic Programming',  difficulty: 'hard',   url: 'https://neetcode.io/problems/burst-balloons',               leetcodeUrl: 'https://leetcode.com/problems/burst-balloons/' },
  { slug: 'regular-expression-matching',  title: 'Regular Expression Matching',                     pattern: '2D Dynamic Programming',  difficulty: 'hard',   url: 'https://neetcode.io/problems/regular-expression-matching',  leetcodeUrl: 'https://leetcode.com/problems/regular-expression-matching/' },

  // Greedy (8)
  { slug: 'maximum-subarray',             title: 'Maximum Subarray',                                pattern: 'Greedy',                  difficulty: 'medium', url: 'https://neetcode.io/problems/maximum-subarray',             leetcodeUrl: 'https://leetcode.com/problems/maximum-subarray/' },
  { slug: 'jump-game',                    title: 'Jump Game',                                       pattern: 'Greedy',                  difficulty: 'medium', url: 'https://neetcode.io/problems/jump-game',                    leetcodeUrl: 'https://leetcode.com/problems/jump-game/' },
  { slug: 'jump-game-ii',                 title: 'Jump Game II',                                    pattern: 'Greedy',                  difficulty: 'medium', url: 'https://neetcode.io/problems/jump-game-ii',                 leetcodeUrl: 'https://leetcode.com/problems/jump-game-ii/' },
  { slug: 'gas-station',                  title: 'Gas Station',                                     pattern: 'Greedy',                  difficulty: 'medium', url: 'https://neetcode.io/problems/gas-station',                  leetcodeUrl: 'https://leetcode.com/problems/gas-station/' },
  { slug: 'hand-of-straights',            title: 'Hand of Straights',                               pattern: 'Greedy',                  difficulty: 'medium', url: 'https://neetcode.io/problems/hand-of-straights',            leetcodeUrl: 'https://leetcode.com/problems/hand-of-straights/' },
  { slug: 'merge-triplets-to-form-target', title: 'Merge Triplets to Form Target Triplet',          pattern: 'Greedy',                  difficulty: 'medium', url: 'https://neetcode.io/problems/merge-triplets-to-form-target', leetcodeUrl: 'https://leetcode.com/problems/merge-triplets-to-form-target-triplet/' },
  { slug: 'partition-labels',             title: 'Partition Labels',                                pattern: 'Greedy',                  difficulty: 'medium', url: 'https://neetcode.io/problems/partition-labels',             leetcodeUrl: 'https://leetcode.com/problems/partition-labels/' },
  { slug: 'valid-parenthesis-string',     title: 'Valid Parenthesis String',                        pattern: 'Greedy',                  difficulty: 'medium', url: 'https://neetcode.io/problems/valid-parenthesis-string',     leetcodeUrl: 'https://leetcode.com/problems/valid-parenthesis-string/' },

  // Intervals (6)
  { slug: 'insert-new-interval',          title: 'Insert Interval',                                 pattern: 'Intervals',               difficulty: 'medium', url: 'https://neetcode.io/problems/insert-new-interval',          leetcodeUrl: 'https://leetcode.com/problems/insert-interval/' },
  { slug: 'merge-intervals',              title: 'Merge Intervals',                                 pattern: 'Intervals',               difficulty: 'medium', url: 'https://neetcode.io/problems/merge-intervals',              leetcodeUrl: 'https://leetcode.com/problems/merge-intervals/' },
  { slug: 'non-overlapping-intervals',    title: 'Non-Overlapping Intervals',                       pattern: 'Intervals',               difficulty: 'medium', url: 'https://neetcode.io/problems/non-overlapping-intervals',    leetcodeUrl: 'https://leetcode.com/problems/non-overlapping-intervals/' },
  { slug: 'meeting-schedule',             title: 'Meeting Rooms',                                   pattern: 'Intervals',               difficulty: 'easy',   url: 'https://neetcode.io/problems/meeting-schedule',             leetcodeUrl: 'https://leetcode.com/problems/meeting-rooms/', leetcodePremium: true },
  { slug: 'meeting-schedule-ii',          title: 'Meeting Rooms II',                                pattern: 'Intervals',               difficulty: 'medium', url: 'https://neetcode.io/problems/meeting-schedule-ii',          leetcodeUrl: 'https://leetcode.com/problems/meeting-rooms-ii/', leetcodePremium: true },
  { slug: 'minimum-interval-including-query', title: 'Minimum Interval to Include Each Query',     pattern: 'Intervals',               difficulty: 'hard',   url: 'https://neetcode.io/problems/minimum-interval-including-query', leetcodeUrl: 'https://leetcode.com/problems/minimum-interval-to-include-each-query/' },

  // Math & Geometry (8)
  { slug: 'rotate-matrix',                title: 'Rotate Image',                                    pattern: 'Math & Geometry',         difficulty: 'medium', url: 'https://neetcode.io/problems/rotate-matrix',                leetcodeUrl: 'https://leetcode.com/problems/rotate-image/' },
  { slug: 'spiral-matrix',                title: 'Spiral Matrix',                                   pattern: 'Math & Geometry',         difficulty: 'medium', url: 'https://neetcode.io/problems/spiral-matrix',                leetcodeUrl: 'https://leetcode.com/problems/spiral-matrix/' },
  { slug: 'zero-matrix',                  title: 'Set Matrix Zeroes',                               pattern: 'Math & Geometry',         difficulty: 'medium', url: 'https://neetcode.io/problems/zero-matrix',                  leetcodeUrl: 'https://leetcode.com/problems/set-matrix-zeroes/' },
  { slug: 'non-cyclical-number',          title: 'Happy Number',                                    pattern: 'Math & Geometry',         difficulty: 'easy',   url: 'https://neetcode.io/problems/non-cyclical-number',          leetcodeUrl: 'https://leetcode.com/problems/happy-number/' },
  { slug: 'plus-one',                     title: 'Plus One',                                        pattern: 'Math & Geometry',         difficulty: 'easy',   url: 'https://neetcode.io/problems/plus-one',                     leetcodeUrl: 'https://leetcode.com/problems/plus-one/' },
  { slug: 'pow-x-n',                      title: 'Pow(x, n)',                                       pattern: 'Math & Geometry',         difficulty: 'medium', url: 'https://neetcode.io/problems/pow-x-n',                      leetcodeUrl: 'https://leetcode.com/problems/powx-n/' },
  { slug: 'multiply-strings',             title: 'Multiply Strings',                                pattern: 'Math & Geometry',         difficulty: 'medium', url: 'https://neetcode.io/problems/multiply-strings',             leetcodeUrl: 'https://leetcode.com/problems/multiply-strings/' },
  { slug: 'count-squares',                title: 'Detect Squares',                                  pattern: 'Math & Geometry',         difficulty: 'medium', url: 'https://neetcode.io/problems/count-squares',                leetcodeUrl: 'https://leetcode.com/problems/detect-squares/' },

  // Bit Manipulation (7)
  { slug: 'single-number',                title: 'Single Number',                                   pattern: 'Bit Manipulation',        difficulty: 'easy',   url: 'https://neetcode.io/problems/single-number',                leetcodeUrl: 'https://leetcode.com/problems/single-number/' },
  { slug: 'number-of-one-bits',           title: 'Number of 1 Bits',                                pattern: 'Bit Manipulation',        difficulty: 'easy',   url: 'https://neetcode.io/problems/number-of-one-bits',           leetcodeUrl: 'https://leetcode.com/problems/number-of-1-bits/' },
  { slug: 'counting-bits',                title: 'Counting Bits',                                   pattern: 'Bit Manipulation',        difficulty: 'easy',   url: 'https://neetcode.io/problems/counting-bits',                leetcodeUrl: 'https://leetcode.com/problems/counting-bits/' },
  { slug: 'reverse-bits',                 title: 'Reverse Bits',                                    pattern: 'Bit Manipulation',        difficulty: 'easy',   url: 'https://neetcode.io/problems/reverse-bits',                 leetcodeUrl: 'https://leetcode.com/problems/reverse-bits/' },
  { slug: 'missing-number',               title: 'Missing Number',                                  pattern: 'Bit Manipulation',        difficulty: 'easy',   url: 'https://neetcode.io/problems/missing-number',               leetcodeUrl: 'https://leetcode.com/problems/missing-number/' },
  { slug: 'sum-of-two-integers',          title: 'Sum of Two Integers',                             pattern: 'Bit Manipulation',        difficulty: 'medium', url: 'https://neetcode.io/problems/sum-of-two-integers',          leetcodeUrl: 'https://leetcode.com/problems/sum-of-two-integers/' },
  { slug: 'reverse-integer',              title: 'Reverse Integer',                                 pattern: 'Bit Manipulation',        difficulty: 'medium', url: 'https://neetcode.io/problems/reverse-integer',              leetcodeUrl: 'https://leetcode.com/problems/reverse-integer/' },
]

const BLIND_75_SLUGS = [
  'two-sum',
  'buy-and-sell-crypto',
  'duplicate-integer',
  'products-of-array-discluding-self',
  'maximum-subarray',
  'maximum-product-subarray',
  'find-minimum-in-rotated-sorted-array',
  'find-target-in-rotated-sorted-array',
  'three-integer-sum',
  'max-water-container',
  'sum-of-two-integers',
  'number-of-one-bits',
  'counting-bits',
  'missing-number',
  'reverse-bits',
  'climbing-stairs',
  'coin-change',
  'longest-increasing-subsequence',
  'longest-common-subsequence',
  'word-break',
  'combination-target-sum',
  'house-robber',
  'house-robber-ii',
  'decode-ways',
  'unique-paths',
  'jump-game',
  'clone-graph',
  'course-schedule',
  'pacific-atlantic-water-flow',
  'number-of-islands',
  'longest-consecutive-sequence',
  'foreign-dictionary',
  'valid-tree',
  'count-connected-components',
  'insert-new-interval',
  'merge-intervals',
  'non-overlapping-intervals',
  'meeting-schedule',
  'meeting-schedule-ii',
  'reverse-a-linked-list',
  'linked-list-cycle-detection',
  'merge-two-sorted-linked-lists',
  'merge-k-sorted-linked-lists',
  'remove-node-from-end-of-linked-list',
  'reorder-linked-list',
  'set-zeroes',
  'spiral-matrix',
  'rotate-matrix',
  'word-search',
  'longest-substring-without-duplicates',
  'longest-repeating-substring-with-replacement',
  'minimum-window-with-characters',
  'valid-anagram',
  'anagram-groups',
  'validate-parentheses',
  'trapping-rain-water',
  'valid-palindrome',
  'longest-palindromic-substring',
  'palindromic-substrings',
  'maximum-depth-of-binary-tree',
  'same-binary-tree',
  'invert-a-binary-tree',
  'binary-tree-maximum-path-sum',
  'binary-tree-level-order-traversal',
  'serialize-and-deserialize-binary-tree',
  'subtree-of-a-binary-tree',
  'construct-binary-tree-from-preorder-and-inorder-traversal',
  'valid-binary-search-tree',
  'kth-smallest-element-in-a-bst',
  'lowest-common-ancestor-of-a-binary-search-tree',
  'implement-trie-prefix-tree',
  'design-add-and-search-words-data-structure',
  'word-search-ii',
  'top-k-frequent-elements',
  'find-median-from-data-stream',
] as const

const LEGACY_SLUG_ALIASES: Record<string, string> = {
  'combination-target-sum': 'combination-target-sum',
  'number-of-islands': 'count-number-of-islands',
  'unique-paths': 'count-paths',
  'set-zeroes': 'zero-matrix',
  'word-search': 'search-for-word',
  'valid-palindrome': 'is-palindrome',
  'maximum-depth-of-binary-tree': 'depth-of-binary-tree',
  'binary-tree-level-order-traversal': 'level-order-traversal-of-binary-tree',
  'construct-binary-tree-from-preorder-and-inorder-traversal': 'binary-tree-from-preorder-and-inorder-traversal',
  'kth-smallest-element-in-a-bst': 'kth-smallest-integer-in-bst',
  'lowest-common-ancestor-of-a-binary-search-tree': 'lowest-common-ancestor-in-binary-search-tree',
  'implement-trie-prefix-tree': 'implement-prefix-tree',
  'design-add-and-search-words-data-structure': 'design-word-search-data-structure',
  'word-search-ii': 'search-for-word-ii',
  'top-k-frequent-elements': 'top-k-elements-in-list',
  'find-median-from-data-stream': 'find-median-in-a-data-stream',
}

const NEETCODE_150_BY_SLUG = new Map(NEETCODE_150.map(problem => [problem.slug, problem]))

export const NEETCODE_75: NeetcodeProblem[] = BLIND_75_SLUGS.map((slug) => {
  const problem = NEETCODE_150_BY_SLUG.get(LEGACY_SLUG_ALIASES[slug] ?? slug)
  if (!problem) throw new Error(`Blind 75 slug is missing from NEETCODE_150: ${slug}`)
  return problem
})

const EXTRA_100: NeetcodeProblem[] = [
  { slug: 'design-hashmap', title: 'Design HashMap', pattern: 'Arrays & Hashing', difficulty: 'easy', url: 'https://neetcode.io/problems/design-hashmap', leetcodeUrl: 'https://leetcode.com/problems/design-hashmap/' },
  { slug: 'design-hashset', title: 'Design HashSet', pattern: 'Arrays & Hashing', difficulty: 'easy', url: 'https://neetcode.io/problems/design-hashset', leetcodeUrl: 'https://leetcode.com/problems/design-hashset/' },
  { slug: 'concatenation-of-array', title: 'Concatenation of Array', pattern: 'Arrays & Hashing', difficulty: 'easy', url: 'https://neetcode.io/problems/concatenation-of-array', leetcodeUrl: 'https://leetcode.com/problems/concatenation-of-array/' },
  { slug: 'replace-elements-with-greatest-element-on-right-side', title: 'Replace Elements with Greatest Element on Right Side', pattern: 'Arrays & Hashing', difficulty: 'easy', url: 'https://neetcode.io/problems/replace-elements-with-greatest-element-on-right-side', leetcodeUrl: 'https://leetcode.com/problems/replace-elements-with-greatest-element-on-right-side/' },
  { slug: 'is-subsequence', title: 'Is Subsequence', pattern: 'Arrays & Hashing', difficulty: 'easy', url: 'https://neetcode.io/problems/is-subsequence', leetcodeUrl: 'https://leetcode.com/problems/is-subsequence/' },
  { slug: 'length-of-last-word', title: 'Length of Last Word', pattern: 'Arrays & Hashing', difficulty: 'easy', url: 'https://neetcode.io/problems/length-of-last-word', leetcodeUrl: 'https://leetcode.com/problems/length-of-last-word/' },
  { slug: 'longest-common-prefix', title: 'Longest Common Prefix', pattern: 'Arrays & Hashing', difficulty: 'easy', url: 'https://neetcode.io/problems/longest-common-prefix', leetcodeUrl: 'https://leetcode.com/problems/longest-common-prefix/' },
  { slug: 'remove-element', title: 'Remove Element', pattern: 'Arrays & Hashing', difficulty: 'easy', url: 'https://neetcode.io/problems/remove-element', leetcodeUrl: 'https://leetcode.com/problems/remove-element/' },
  { slug: 'majority-element', title: 'Majority Element', pattern: 'Arrays & Hashing', difficulty: 'easy', url: 'https://neetcode.io/problems/majority-element', leetcodeUrl: 'https://leetcode.com/problems/majority-element/' },
  { slug: 'remove-duplicates-from-sorted-array', title: 'Remove Duplicates from Sorted Array', pattern: 'Arrays & Hashing', difficulty: 'easy', url: 'https://neetcode.io/problems/remove-duplicates-from-sorted-array', leetcodeUrl: 'https://leetcode.com/problems/remove-duplicates-from-sorted-array/' },
  { slug: 'sort-colors', title: 'Sort Colors', pattern: 'Arrays & Hashing', difficulty: 'medium', url: 'https://neetcode.io/problems/sort-colors', leetcodeUrl: 'https://leetcode.com/problems/sort-colors/' },
  { slug: '4sum', title: '4Sum', pattern: 'Arrays & Hashing', difficulty: 'medium', url: 'https://neetcode.io/problems/4sum', leetcodeUrl: 'https://leetcode.com/problems/4sum/' },
  { slug: 'subarray-sum-equals-k', title: 'Subarray Sum Equals K', pattern: 'Arrays & Hashing', difficulty: 'medium', url: 'https://neetcode.io/problems/subarray-sum-equals-k', leetcodeUrl: 'https://leetcode.com/problems/subarray-sum-equals-k/' },
  { slug: 'move-zeroes', title: 'Move Zeroes', pattern: 'Two Pointers', difficulty: 'easy', url: 'https://neetcode.io/problems/move-zeroes', leetcodeUrl: 'https://leetcode.com/problems/move-zeroes/' },
  { slug: 'remove-duplicates-from-sorted-array-ii', title: 'Remove Duplicates from Sorted Array II', pattern: 'Two Pointers', difficulty: 'medium', url: 'https://neetcode.io/problems/remove-duplicates-from-sorted-array-ii', leetcodeUrl: 'https://leetcode.com/problems/remove-duplicates-from-sorted-array-ii/' },
  { slug: 'valid-palindrome-ii', title: 'Valid Palindrome II', pattern: 'Two Pointers', difficulty: 'easy', url: 'https://neetcode.io/problems/valid-palindrome-ii', leetcodeUrl: 'https://leetcode.com/problems/valid-palindrome-ii/' },
  { slug: 'merge-sorted-array', title: 'Merge Sorted Array', pattern: 'Two Pointers', difficulty: 'easy', url: 'https://neetcode.io/problems/merge-sorted-array', leetcodeUrl: 'https://leetcode.com/problems/merge-sorted-array/' },
  { slug: 'squares-of-a-sorted-array', title: 'Squares of a Sorted Array', pattern: 'Two Pointers', difficulty: 'easy', url: 'https://neetcode.io/problems/squares-of-a-sorted-array', leetcodeUrl: 'https://leetcode.com/problems/squares-of-a-sorted-array/' },
  { slug: 'sort-array-by-parity', title: 'Sort Array By Parity', pattern: 'Two Pointers', difficulty: 'easy', url: 'https://neetcode.io/problems/sort-array-by-parity', leetcodeUrl: 'https://leetcode.com/problems/sort-array-by-parity/' },
  { slug: 'boats-to-save-people', title: 'Boats to Save People', pattern: 'Two Pointers', difficulty: 'medium', url: 'https://neetcode.io/problems/boats-to-save-people', leetcodeUrl: 'https://leetcode.com/problems/boats-to-save-people/' },
  { slug: 'next-permutation', title: 'Next Permutation', pattern: 'Two Pointers', difficulty: 'medium', url: 'https://neetcode.io/problems/next-permutation', leetcodeUrl: 'https://leetcode.com/problems/next-permutation/' },
  { slug: 'maximum-average-subarray-i', title: 'Maximum Average Subarray I', pattern: 'Sliding Window', difficulty: 'easy', url: 'https://neetcode.io/problems/maximum-average-subarray-i', leetcodeUrl: 'https://leetcode.com/problems/maximum-average-subarray-i/' },
  { slug: 'max-consecutive-ones-iii', title: 'Max Consecutive Ones III', pattern: 'Sliding Window', difficulty: 'medium', url: 'https://neetcode.io/problems/max-consecutive-ones-iii', leetcodeUrl: 'https://leetcode.com/problems/max-consecutive-ones-iii/' },
  { slug: 'fruit-into-baskets', title: 'Fruit Into Baskets', pattern: 'Sliding Window', difficulty: 'medium', url: 'https://neetcode.io/problems/fruit-into-baskets', leetcodeUrl: 'https://leetcode.com/problems/fruit-into-baskets/' },
  { slug: 'baseball-game', title: 'Baseball Game', pattern: 'Stack', difficulty: 'easy', url: 'https://neetcode.io/problems/baseball-game', leetcodeUrl: 'https://leetcode.com/problems/baseball-game/' },
  { slug: 'backspace-string-compare', title: 'Backspace String Compare', pattern: 'Stack', difficulty: 'easy', url: 'https://neetcode.io/problems/backspace-string-compare', leetcodeUrl: 'https://leetcode.com/problems/backspace-string-compare/' },
  { slug: 'remove-all-adjacent-duplicates-in-string', title: 'Remove All Adjacent Duplicates In String', pattern: 'Stack', difficulty: 'easy', url: 'https://neetcode.io/problems/remove-all-adjacent-duplicates-in-string', leetcodeUrl: 'https://leetcode.com/problems/remove-all-adjacent-duplicates-in-string/' },
  { slug: 'online-stock-span', title: 'Online Stock Span', pattern: 'Stack', difficulty: 'medium', url: 'https://neetcode.io/problems/online-stock-span', leetcodeUrl: 'https://leetcode.com/problems/online-stock-span/' },
  { slug: 'simplify-path', title: 'Simplify Path', pattern: 'Stack', difficulty: 'medium', url: 'https://neetcode.io/problems/simplify-path', leetcodeUrl: 'https://leetcode.com/problems/simplify-path/' },
  { slug: 'decode-string', title: 'Decode String', pattern: 'Stack', difficulty: 'medium', url: 'https://neetcode.io/problems/decode-string', leetcodeUrl: 'https://leetcode.com/problems/decode-string/' },
  { slug: 'asteroid-collision', title: 'Asteroid Collision', pattern: 'Stack', difficulty: 'medium', url: 'https://neetcode.io/problems/asteroid-collision', leetcodeUrl: 'https://leetcode.com/problems/asteroid-collision/' },
  { slug: 'guess-number-higher-or-lower', title: 'Guess Number Higher or Lower', pattern: 'Binary Search', difficulty: 'easy', url: 'https://neetcode.io/problems/guess-number-higher-or-lower', leetcodeUrl: 'https://leetcode.com/problems/guess-number-higher-or-lower/' },
  { slug: 'first-bad-version', title: 'First Bad Version', pattern: 'Binary Search', difficulty: 'easy', url: 'https://neetcode.io/problems/first-bad-version', leetcodeUrl: 'https://leetcode.com/problems/first-bad-version/' },
  { slug: 'sqrtx', title: 'Sqrt(x)', pattern: 'Binary Search', difficulty: 'easy', url: 'https://neetcode.io/problems/sqrtx', leetcodeUrl: 'https://leetcode.com/problems/sqrtx/' },
  { slug: 'search-insert-position', title: 'Search Insert Position', pattern: 'Binary Search', difficulty: 'easy', url: 'https://neetcode.io/problems/search-insert-position', leetcodeUrl: 'https://leetcode.com/problems/search-insert-position/' },
  { slug: 'successful-pairs-of-spells-and-potions', title: 'Successful Pairs of Spells and Potions', pattern: 'Binary Search', difficulty: 'medium', url: 'https://neetcode.io/problems/successful-pairs-of-spells-and-potions', leetcodeUrl: 'https://leetcode.com/problems/successful-pairs-of-spells-and-potions/' },
  { slug: 'capacity-to-ship-packages-within-d-days', title: 'Capacity To Ship Packages Within D Days', pattern: 'Binary Search', difficulty: 'medium', url: 'https://neetcode.io/problems/capacity-to-ship-packages-within-d-days', leetcodeUrl: 'https://leetcode.com/problems/capacity-to-ship-packages-within-d-days/' },
  { slug: 'split-array-largest-sum', title: 'Split Array Largest Sum', pattern: 'Binary Search', difficulty: 'hard', url: 'https://neetcode.io/problems/split-array-largest-sum', leetcodeUrl: 'https://leetcode.com/problems/split-array-largest-sum/' },
  { slug: 'middle-of-the-linked-list', title: 'Middle of the Linked List', pattern: 'Linked List', difficulty: 'easy', url: 'https://neetcode.io/problems/middle-of-the-linked-list', leetcodeUrl: 'https://leetcode.com/problems/middle-of-the-linked-list/' },
  { slug: 'remove-linked-list-elements', title: 'Remove Linked List Elements', pattern: 'Linked List', difficulty: 'easy', url: 'https://neetcode.io/problems/remove-linked-list-elements', leetcodeUrl: 'https://leetcode.com/problems/remove-linked-list-elements/' },
  { slug: 'design-linked-list', title: 'Design Linked List', pattern: 'Linked List', difficulty: 'medium', url: 'https://neetcode.io/problems/design-linked-list', leetcodeUrl: 'https://leetcode.com/problems/design-linked-list/' },
  { slug: 'path-sum', title: 'Path Sum', pattern: 'Trees', difficulty: 'easy', url: 'https://neetcode.io/problems/path-sum', leetcodeUrl: 'https://leetcode.com/problems/path-sum/' },
  { slug: 'binary-tree-inorder-traversal', title: 'Binary Tree Inorder Traversal', pattern: 'Trees', difficulty: 'easy', url: 'https://neetcode.io/problems/binary-tree-inorder-traversal', leetcodeUrl: 'https://leetcode.com/problems/binary-tree-inorder-traversal/' },
  { slug: 'binary-tree-preorder-traversal', title: 'Binary Tree Preorder Traversal', pattern: 'Trees', difficulty: 'easy', url: 'https://neetcode.io/problems/binary-tree-preorder-traversal', leetcodeUrl: 'https://leetcode.com/problems/binary-tree-preorder-traversal/' },
  { slug: 'binary-tree-postorder-traversal', title: 'Binary Tree Postorder Traversal', pattern: 'Trees', difficulty: 'easy', url: 'https://neetcode.io/problems/binary-tree-postorder-traversal', leetcodeUrl: 'https://leetcode.com/problems/binary-tree-postorder-traversal/' },
  { slug: 'minimum-depth-of-binary-tree', title: 'Minimum Depth of Binary Tree', pattern: 'Trees', difficulty: 'easy', url: 'https://neetcode.io/problems/minimum-depth-of-binary-tree', leetcodeUrl: 'https://leetcode.com/problems/minimum-depth-of-binary-tree/' },
  { slug: 'path-sum-ii', title: 'Path Sum II', pattern: 'Trees', difficulty: 'medium', url: 'https://neetcode.io/problems/path-sum-ii', leetcodeUrl: 'https://leetcode.com/problems/path-sum-ii/' },
  { slug: 'sum-root-to-leaf-numbers', title: 'Sum Root to Leaf Numbers', pattern: 'Trees', difficulty: 'medium', url: 'https://neetcode.io/problems/sum-root-to-leaf-numbers', leetcodeUrl: 'https://leetcode.com/problems/sum-root-to-leaf-numbers/' },
  { slug: 'delete-node-in-a-bst', title: 'Delete Node in a BST', pattern: 'Trees', difficulty: 'medium', url: 'https://neetcode.io/problems/delete-node-in-a-bst', leetcodeUrl: 'https://leetcode.com/problems/delete-node-in-a-bst/' },
  { slug: 'find-median-from-data-stream', title: 'Find Median from Data Stream', pattern: 'Heap / Priority Queue', difficulty: 'hard', url: 'https://neetcode.io/problems/find-median-from-data-stream', leetcodeUrl: 'https://leetcode.com/problems/find-median-from-data-stream/' },
  { slug: 'task-scheduler', title: 'Task Scheduler', pattern: 'Heap / Priority Queue', difficulty: 'medium', url: 'https://neetcode.io/problems/task-scheduler', leetcodeUrl: 'https://leetcode.com/problems/task-scheduler/' },
  { slug: 'reorganize-string', title: 'Reorganize String', pattern: 'Heap / Priority Queue', difficulty: 'medium', url: 'https://neetcode.io/problems/reorganize-string', leetcodeUrl: 'https://leetcode.com/problems/reorganize-string/' },
  { slug: 'single-threaded-cpu', title: 'Single-Threaded CPU', pattern: 'Heap / Priority Queue', difficulty: 'medium', url: 'https://neetcode.io/problems/single-threaded-cpu', leetcodeUrl: 'https://leetcode.com/problems/single-threaded-cpu/' },
  { slug: 'ipo', title: 'IPO', pattern: 'Heap / Priority Queue', difficulty: 'hard', url: 'https://neetcode.io/problems/ipo', leetcodeUrl: 'https://leetcode.com/problems/ipo/' },
  { slug: 'permutations-ii', title: 'Permutations II', pattern: 'Backtracking', difficulty: 'medium', url: 'https://neetcode.io/problems/permutations-ii', leetcodeUrl: 'https://leetcode.com/problems/permutations-ii/' },
  { slug: 'combination-sum-iii', title: 'Combination Sum III', pattern: 'Backtracking', difficulty: 'medium', url: 'https://neetcode.io/problems/combination-sum-iii', leetcodeUrl: 'https://leetcode.com/problems/combination-sum-iii/' },
  { slug: 'restore-ip-addresses', title: 'Restore IP Addresses', pattern: 'Backtracking', difficulty: 'medium', url: 'https://neetcode.io/problems/restore-ip-addresses', leetcodeUrl: 'https://leetcode.com/problems/restore-ip-addresses/' },
  { slug: 'beautiful-arrangement', title: 'Beautiful Arrangement', pattern: 'Backtracking', difficulty: 'medium', url: 'https://neetcode.io/problems/beautiful-arrangement', leetcodeUrl: 'https://leetcode.com/problems/beautiful-arrangement/' },
  { slug: 'matchsticks-to-square', title: 'Matchsticks to Square', pattern: 'Backtracking', difficulty: 'medium', url: 'https://neetcode.io/problems/matchsticks-to-square', leetcodeUrl: 'https://leetcode.com/problems/matchsticks-to-square/' },
  { slug: 'partition-to-k-equal-sum-subsets', title: 'Partition to K Equal Sum Subsets', pattern: 'Backtracking', difficulty: 'medium', url: 'https://neetcode.io/problems/partition-to-k-equal-sum-subsets', leetcodeUrl: 'https://leetcode.com/problems/partition-to-k-equal-sum-subsets/' },
  { slug: 'letter-tile-possibilities', title: 'Letter Tile Possibilities', pattern: 'Backtracking', difficulty: 'medium', url: 'https://neetcode.io/problems/letter-tile-possibilities', leetcodeUrl: 'https://leetcode.com/problems/letter-tile-possibilities/' },
  { slug: 'n-queens-ii', title: 'N-Queens II', pattern: 'Backtracking', difficulty: 'hard', url: 'https://neetcode.io/problems/n-queens-ii', leetcodeUrl: 'https://leetcode.com/problems/n-queens-ii/' },
  { slug: 'maximum-xor-of-two-numbers-in-an-array', title: 'Maximum XOR of Two Numbers in an Array', pattern: 'Tries', difficulty: 'medium', url: 'https://neetcode.io/problems/maximum-xor-of-two-numbers-in-an-array', leetcodeUrl: 'https://leetcode.com/problems/maximum-xor-of-two-numbers-in-an-array/' },
  { slug: 'keys-and-rooms', title: 'Keys and Rooms', pattern: 'Graphs', difficulty: 'medium', url: 'https://neetcode.io/problems/keys-and-rooms', leetcodeUrl: 'https://leetcode.com/problems/keys-and-rooms/' },
  { slug: 'island-perimeter', title: 'Island Perimeter', pattern: 'Graphs', difficulty: 'easy', url: 'https://neetcode.io/problems/island-perimeter', leetcodeUrl: 'https://leetcode.com/problems/island-perimeter/' },
  { slug: 'evaluate-division', title: 'Evaluate Division', pattern: 'Graphs', difficulty: 'medium', url: 'https://neetcode.io/problems/evaluate-division', leetcodeUrl: 'https://leetcode.com/problems/evaluate-division/' },
  { slug: 'minimum-height-trees', title: 'Minimum Height Trees', pattern: 'Graphs', difficulty: 'medium', url: 'https://neetcode.io/problems/minimum-height-trees', leetcodeUrl: 'https://leetcode.com/problems/minimum-height-trees/' },
  { slug: 'open-the-lock', title: 'Open the Lock', pattern: 'Graphs', difficulty: 'medium', url: 'https://neetcode.io/problems/open-the-lock', leetcodeUrl: 'https://leetcode.com/problems/open-the-lock/' },
  { slug: 'accounts-merge', title: 'Accounts Merge', pattern: 'Graphs', difficulty: 'medium', url: 'https://neetcode.io/problems/accounts-merge', leetcodeUrl: 'https://leetcode.com/problems/accounts-merge/' },
  { slug: 'find-the-town-judge', title: 'Find the Town Judge', pattern: 'Graphs', difficulty: 'easy', url: 'https://neetcode.io/problems/find-the-town-judge', leetcodeUrl: 'https://leetcode.com/problems/find-the-town-judge/' },
  { slug: 'course-schedule-iv', title: 'Course Schedule IV', pattern: 'Graphs', difficulty: 'medium', url: 'https://neetcode.io/problems/course-schedule-iv', leetcodeUrl: 'https://leetcode.com/problems/course-schedule-iv/' },
  { slug: 'path-with-minimum-effort', title: 'Path With Minimum Effort', pattern: 'Advanced Graphs', difficulty: 'medium', url: 'https://neetcode.io/problems/path-with-minimum-effort', leetcodeUrl: 'https://leetcode.com/problems/path-with-minimum-effort/' },
  { slug: 'find-critical-and-pseudo-critical-edges-in-minimum-spanning-tree', title: 'Find Critical and Pseudo-Critical Edges in Minimum Spanning Tree', pattern: 'Advanced Graphs', difficulty: 'hard', url: 'https://neetcode.io/problems/find-critical-and-pseudo-critical-edges-in-minimum-spanning-tree', leetcodeUrl: 'https://leetcode.com/problems/find-critical-and-pseudo-critical-edges-in-minimum-spanning-tree/' },
  { slug: 'greatest-common-divisor-traversal', title: 'Greatest Common Divisor Traversal', pattern: 'Advanced Graphs', difficulty: 'hard', url: 'https://neetcode.io/problems/greatest-common-divisor-traversal', leetcodeUrl: 'https://leetcode.com/problems/greatest-common-divisor-traversal/' },
  { slug: 'minimum-cost-to-make-at-least-one-valid-path-in-a-grid', title: 'Minimum Cost to Make at Least One Valid Path in a Grid', pattern: 'Advanced Graphs', difficulty: 'hard', url: 'https://neetcode.io/problems/minimum-cost-to-make-at-least-one-valid-path-in-a-grid', leetcodeUrl: 'https://leetcode.com/problems/minimum-cost-to-make-at-least-one-valid-path-in-a-grid/' },
  { slug: 'n-th-tribonacci-number', title: 'N-th Tribonacci Number', pattern: '1D Dynamic Programming', difficulty: 'easy', url: 'https://neetcode.io/problems/n-th-tribonacci-number', leetcodeUrl: 'https://leetcode.com/problems/n-th-tribonacci-number/' },
  { slug: 'perfect-squares', title: 'Perfect Squares', pattern: '1D Dynamic Programming', difficulty: 'medium', url: 'https://neetcode.io/problems/perfect-squares', leetcodeUrl: 'https://leetcode.com/problems/perfect-squares/' },
  { slug: 'integer-break', title: 'Integer Break', pattern: '1D Dynamic Programming', difficulty: 'medium', url: 'https://neetcode.io/problems/integer-break', leetcodeUrl: 'https://leetcode.com/problems/integer-break/' },
  { slug: 'combination-sum-iv', title: 'Combination Sum IV', pattern: '1D Dynamic Programming', difficulty: 'medium', url: 'https://neetcode.io/problems/combination-sum-iv', leetcodeUrl: 'https://leetcode.com/problems/combination-sum-iv/' },
  { slug: 'extra-characters-in-a-string', title: 'Extra Characters in a String', pattern: '1D Dynamic Programming', difficulty: 'medium', url: 'https://neetcode.io/problems/extra-characters-in-a-string', leetcodeUrl: 'https://leetcode.com/problems/extra-characters-in-a-string/' },
  { slug: 'stone-game-ii', title: 'Stone Game II', pattern: '2D Dynamic Programming', difficulty: 'medium', url: 'https://neetcode.io/problems/stone-game-ii', leetcodeUrl: 'https://leetcode.com/problems/stone-game-ii/' },
  { slug: 'stone-game-iii', title: 'Stone Game III', pattern: '2D Dynamic Programming', difficulty: 'hard', url: 'https://neetcode.io/problems/stone-game-iii', leetcodeUrl: 'https://leetcode.com/problems/stone-game-iii/' },
  { slug: 'longest-turbulent-subarray', title: 'Longest Turbulent Subarray', pattern: '2D Dynamic Programming', difficulty: 'medium', url: 'https://neetcode.io/problems/longest-turbulent-subarray', leetcodeUrl: 'https://leetcode.com/problems/longest-turbulent-subarray/' },
  { slug: 'maximum-sum-circular-subarray', title: 'Maximum Sum Circular Subarray', pattern: '2D Dynamic Programming', difficulty: 'medium', url: 'https://neetcode.io/problems/maximum-sum-circular-subarray', leetcodeUrl: 'https://leetcode.com/problems/maximum-sum-circular-subarray/' },
  { slug: 'last-stone-weight-ii', title: 'Last Stone Weight II', pattern: '2D Dynamic Programming', difficulty: 'medium', url: 'https://neetcode.io/problems/last-stone-weight-ii', leetcodeUrl: 'https://leetcode.com/problems/last-stone-weight-ii/' },
  { slug: 'dota2-senate', title: 'Dota2 Senate', pattern: 'Greedy', difficulty: 'medium', url: 'https://neetcode.io/problems/dota2-senate', leetcodeUrl: 'https://leetcode.com/problems/dota2-senate/' },
  { slug: 'lemonade-change', title: 'Lemonade Change', pattern: 'Greedy', difficulty: 'easy', url: 'https://neetcode.io/problems/lemonade-change', leetcodeUrl: 'https://leetcode.com/problems/lemonade-change/' },
  { slug: 'longest-happy-string', title: 'Longest Happy String', pattern: 'Greedy', difficulty: 'medium', url: 'https://neetcode.io/problems/longest-happy-string', leetcodeUrl: 'https://leetcode.com/problems/longest-happy-string/' },
  { slug: 'car-pooling', title: 'Car Pooling', pattern: 'Greedy', difficulty: 'medium', url: 'https://neetcode.io/problems/car-pooling', leetcodeUrl: 'https://leetcode.com/problems/car-pooling/' },
  { slug: 'queue-reconstruction-by-height', title: 'Queue Reconstruction by Height', pattern: 'Greedy', difficulty: 'medium', url: 'https://neetcode.io/problems/queue-reconstruction-by-height', leetcodeUrl: 'https://leetcode.com/problems/queue-reconstruction-by-height/' },
  { slug: 'minimum-number-of-arrows-to-burst-balloons', title: 'Minimum Number of Arrows to Burst Balloons', pattern: 'Greedy', difficulty: 'medium', url: 'https://neetcode.io/problems/minimum-number-of-arrows-to-burst-balloons', leetcodeUrl: 'https://leetcode.com/problems/minimum-number-of-arrows-to-burst-balloons/' },
  { slug: 'meeting-rooms-iii', title: 'Meeting Rooms III', pattern: 'Intervals', difficulty: 'hard', url: 'https://neetcode.io/problems/meeting-rooms-iii', leetcodeUrl: 'https://leetcode.com/problems/meeting-rooms-iii/' },
  { slug: 'greatest-common-divisor-of-strings', title: 'Greatest Common Divisor of Strings', pattern: 'Math & Geometry', difficulty: 'easy', url: 'https://neetcode.io/problems/greatest-common-divisor-of-strings', leetcodeUrl: 'https://leetcode.com/problems/greatest-common-divisor-of-strings/' },
  { slug: 'sum-of-all-subset-xor-totals', title: 'Sum of All Subset XOR Totals', pattern: 'Math & Geometry', difficulty: 'easy', url: 'https://neetcode.io/problems/sum-of-all-subset-xor-totals', leetcodeUrl: 'https://leetcode.com/problems/sum-of-all-subset-xor-totals/' },
  { slug: 'construct-quad-tree', title: 'Construct Quad Tree', pattern: 'Math & Geometry', difficulty: 'medium', url: 'https://neetcode.io/problems/construct-quad-tree', leetcodeUrl: 'https://leetcode.com/problems/construct-quad-tree/' },
  { slug: 'insert-greatest-common-divisors-in-linked-list', title: 'Insert Greatest Common Divisors in Linked List', pattern: 'Math & Geometry', difficulty: 'medium', url: 'https://neetcode.io/problems/insert-greatest-common-divisors-in-linked-list', leetcodeUrl: 'https://leetcode.com/problems/insert-greatest-common-divisors-in-linked-list/' },
  { slug: 'excel-sheet-column-title', title: 'Excel Sheet Column Title', pattern: 'Math & Geometry', difficulty: 'easy', url: 'https://neetcode.io/problems/excel-sheet-column-title', leetcodeUrl: 'https://leetcode.com/problems/excel-sheet-column-title/' },
  { slug: 'bitwise-and-of-numbers-range', title: 'Bitwise AND of Numbers Range', pattern: 'Bit Manipulation', difficulty: 'medium', url: 'https://neetcode.io/problems/bitwise-and-of-numbers-range', leetcodeUrl: 'https://leetcode.com/problems/bitwise-and-of-numbers-range/' },
  { slug: 'hamming-distance', title: 'Hamming Distance', pattern: 'Bit Manipulation', difficulty: 'easy', url: 'https://neetcode.io/problems/hamming-distance', leetcodeUrl: 'https://leetcode.com/problems/hamming-distance/' },
  { slug: 'power-of-two', title: 'Power of Two', pattern: 'Bit Manipulation', difficulty: 'easy', url: 'https://neetcode.io/problems/power-of-two', leetcodeUrl: 'https://leetcode.com/problems/power-of-two/' },
]

export const NEETCODE_250: NeetcodeProblem[] = [...NEETCODE_150, ...EXTRA_100]

export const TRACK_PROBLEMS: Record<DsaTrack, Set<string>> = {
  '75': new Set(NEETCODE_75.map(problem => problem.slug)),
  '150': new Set(NEETCODE_150.map(problem => problem.slug)),
  '250': new Set(NEETCODE_250.map(problem => problem.slug)),
}
